-- made by tncli probe-tests from the player's gun_actions.lua; do not edit
TESTS = {
  { name = "single:BOMB", deck = { "BOMB" } },
  { name = "single:LIGHT_BULLET", deck = { "LIGHT_BULLET" } },
  { name = "single:LIGHT_BULLET_TRIGGER", deck = { "LIGHT_BULLET_TRIGGER" } },
  { name = "single:LIGHT_BULLET_TRIGGER_2", deck = { "LIGHT_BULLET_TRIGGER_2" } },
  { name = "single:LIGHT_BULLET_TIMER", deck = { "LIGHT_BULLET_TIMER" } },
  { name = "single:BULLET", deck = { "BULLET" } },
  { name = "single:BULLET_TRIGGER", deck = { "BULLET_TRIGGER" } },
  { name = "single:BULLET_TIMER", deck = { "BULLET_TIMER" } },
  { name = "single:HEAVY_BULLET", deck = { "HEAVY_BULLET" } },
  { name = "single:HEAVY_BULLET_TRIGGER", deck = { "HEAVY_BULLET_TRIGGER" } },
  { name = "single:HEAVY_BULLET_TIMER", deck = { "HEAVY_BULLET_TIMER" } },
  { name = "single:AIR_BULLET", deck = { "AIR_BULLET" } },
  { name = "single:SLOW_BULLET", deck = { "SLOW_BULLET" } },
  { name = "single:SLOW_BULLET_TRIGGER", deck = { "SLOW_BULLET_TRIGGER" } },
  { name = "single:SLOW_BULLET_TIMER", deck = { "SLOW_BULLET_TIMER" } },
  { name = "single:HOOK", deck = { "HOOK" } },
  { name = "single:BLACK_HOLE", deck = { "BLACK_HOLE" } },
  { name = "single:BLACK_HOLE_DEATH_TRIGGER", deck = { "BLACK_HOLE_DEATH_TRIGGER" } },
  { name = "single:WHITE_HOLE", deck = { "WHITE_HOLE" } },
  { name = "single:BLACK_HOLE_BIG", deck = { "BLACK_HOLE_BIG" } },
  { name = "single:WHITE_HOLE_BIG", deck = { "WHITE_HOLE_BIG" } },
  { name = "single:BLACK_HOLE_GIGA", deck = { "BLACK_HOLE_GIGA" } },
  { name = "single:WHITE_HOLE_GIGA", deck = { "WHITE_HOLE_GIGA" } },
  { name = "single:TENTACLE_PORTAL", deck = { "TENTACLE_PORTAL" } },
  { name = "single:SPITTER", deck = { "SPITTER" } },
  { name = "single:SPITTER_TIMER", deck = { "SPITTER_TIMER" } },
  { name = "single:SPITTER_TIER_2", deck = { "SPITTER_TIER_2" } },
  { name = "single:SPITTER_TIER_2_TIMER", deck = { "SPITTER_TIER_2_TIMER" } },
  { name = "single:SPITTER_TIER_3", deck = { "SPITTER_TIER_3" } },
  { name = "single:SPITTER_TIER_3_TIMER", deck = { "SPITTER_TIER_3_TIMER" } },
  { name = "single:BUBBLESHOT", deck = { "BUBBLESHOT" } },
  { name = "single:BUBBLESHOT_TRIGGER", deck = { "BUBBLESHOT_TRIGGER" } },
  { name = "single:DISC_BULLET", deck = { "DISC_BULLET" } },
  { name = "single:DISC_BULLET_BIG", deck = { "DISC_BULLET_BIG" } },
  { name = "single:DISC_BULLET_BIGGER", deck = { "DISC_BULLET_BIGGER" } },
  { name = "single:BOUNCY_ORB", deck = { "BOUNCY_ORB" } },
  { name = "single:BOUNCY_ORB_TIMER", deck = { "BOUNCY_ORB_TIMER" } },
  { name = "single:RUBBER_BALL", deck = { "RUBBER_BALL" } },
  { name = "single:ARROW", deck = { "ARROW" } },
  { name = "single:POLLEN", deck = { "POLLEN" } },
  { name = "single:LANCE", deck = { "LANCE" } },
  { name = "single:LANCE_HOLY", deck = { "LANCE_HOLY" } },
  { name = "single:ROCKET", deck = { "ROCKET" } },
  { name = "single:ROCKET_TIER_2", deck = { "ROCKET_TIER_2" } },
  { name = "single:ROCKET_TIER_3", deck = { "ROCKET_TIER_3" } },
  { name = "single:GRENADE", deck = { "GRENADE" } },
  { name = "single:GRENADE_TRIGGER", deck = { "GRENADE_TRIGGER" } },
  { name = "single:GRENADE_TIER_2", deck = { "GRENADE_TIER_2" } },
  { name = "single:GRENADE_TIER_3", deck = { "GRENADE_TIER_3" } },
  { name = "single:GRENADE_ANTI", deck = { "GRENADE_ANTI" } },
  { name = "single:GRENADE_LARGE", deck = { "GRENADE_LARGE" } },
  { name = "single:MINE", deck = { "MINE" } },
  { name = "single:MINE_DEATH_TRIGGER", deck = { "MINE_DEATH_TRIGGER" } },
  { name = "single:PIPE_BOMB", deck = { "PIPE_BOMB" } },
  { name = "single:PIPE_BOMB_DEATH_TRIGGER", deck = { "PIPE_BOMB_DEATH_TRIGGER" } },
  { name = "single:FISH", deck = { "FISH" } },
  { name = "single:EXPLODING_DEER", deck = { "EXPLODING_DEER" } },
  { name = "single:EXPLODING_DUCKS", deck = { "EXPLODING_DUCKS" } },
  { name = "single:WORM_SHOT", deck = { "WORM_SHOT" } },
  { name = "single:BOMB_DETONATOR", deck = { "BOMB_DETONATOR" } },
  { name = "single:LASER", deck = { "LASER" } },
  { name = "single:MEGALASER", deck = { "MEGALASER" } },
  { name = "single:LIGHTNING", deck = { "LIGHTNING" } },
  { name = "single:BALL_LIGHTNING", deck = { "BALL_LIGHTNING" } },
  { name = "single:LASER_EMITTER", deck = { "LASER_EMITTER" } },
  { name = "single:LASER_EMITTER_FOUR", deck = { "LASER_EMITTER_FOUR" } },
  { name = "single:LASER_EMITTER_CUTTER", deck = { "LASER_EMITTER_CUTTER" } },
  { name = "single:DIGGER", deck = { "DIGGER" } },
  { name = "single:POWERDIGGER", deck = { "POWERDIGGER" } },
  { name = "single:CHAINSAW", deck = { "CHAINSAW" } },
  { name = "single:LUMINOUS_DRILL", deck = { "LUMINOUS_DRILL" } },
  { name = "single:LASER_LUMINOUS_DRILL", deck = { "LASER_LUMINOUS_DRILL" } },
  { name = "single:TENTACLE", deck = { "TENTACLE" } },
  { name = "single:TENTACLE_TIMER", deck = { "TENTACLE_TIMER" } },
  { name = "single:HEAL_BULLET", deck = { "HEAL_BULLET" } },
  { name = "single:ANTIHEAL", deck = { "ANTIHEAL" } },
  { name = "single:SPIRAL_SHOT", deck = { "SPIRAL_SHOT" } },
  { name = "single:MAGIC_SHIELD", deck = { "MAGIC_SHIELD" } },
  { name = "single:BIG_MAGIC_SHIELD", deck = { "BIG_MAGIC_SHIELD" } },
  { name = "single:CHAIN_BOLT", deck = { "CHAIN_BOLT" } },
  { name = "single:FIREBALL", deck = { "FIREBALL" } },
  { name = "single:METEOR", deck = { "METEOR" } },
  { name = "single:FLAMETHROWER", deck = { "FLAMETHROWER" } },
  { name = "single:ICEBALL", deck = { "ICEBALL" } },
  { name = "single:SLIMEBALL", deck = { "SLIMEBALL" } },
  { name = "single:DARKFLAME", deck = { "DARKFLAME" } },
  { name = "single:MISSILE", deck = { "MISSILE" } },
  { name = "single:FUNKY_SPELL", deck = { "FUNKY_SPELL" } },
  { name = "single:PEBBLE", deck = { "PEBBLE" } },
  { name = "single:DYNAMITE", deck = { "DYNAMITE" } },
  { name = "single:GLITTER_BOMB", deck = { "GLITTER_BOMB" } },
  { name = "single:BUCKSHOT", deck = { "BUCKSHOT" } },
  { name = "single:FREEZING_GAZE", deck = { "FREEZING_GAZE" } },
  { name = "single:GLOWING_BOLT", deck = { "GLOWING_BOLT" } },
  { name = "single:SPORE_POD", deck = { "SPORE_POD" } },
  { name = "single:GLUE_SHOT", deck = { "GLUE_SHOT" } },
  { name = "single:BOMB_HOLY", deck = { "BOMB_HOLY" } },
  { name = "single:BOMB_HOLY_GIGA", deck = { "BOMB_HOLY_GIGA" } },
  { name = "single:PROPANE_TANK", deck = { "PROPANE_TANK" } },
  { name = "single:BOMB_CART", deck = { "BOMB_CART" } },
  { name = "single:CURSED_ORB", deck = { "CURSED_ORB" } },
  { name = "single:EXPANDING_ORB", deck = { "EXPANDING_ORB" } },
  { name = "single:CRUMBLING_EARTH", deck = { "CRUMBLING_EARTH" } },
  { name = "single:SUMMON_ROCK", deck = { "SUMMON_ROCK" } },
  { name = "single:SUMMON_EGG", deck = { "SUMMON_EGG" } },
  { name = "single:SUMMON_HOLLOW_EGG", deck = { "SUMMON_HOLLOW_EGG" } },
  { name = "single:TNTBOX", deck = { "TNTBOX" } },
  { name = "single:TNTBOX_BIG", deck = { "TNTBOX_BIG" } },
  { name = "single:SWARM_FLY", deck = { "SWARM_FLY" } },
  { name = "single:SWARM_FIREBUG", deck = { "SWARM_FIREBUG" } },
  { name = "single:SWARM_WASP", deck = { "SWARM_WASP" } },
  { name = "single:FRIEND_FLY", deck = { "FRIEND_FLY" } },
  { name = "single:ACIDSHOT", deck = { "ACIDSHOT" } },
  { name = "single:THUNDERBALL", deck = { "THUNDERBALL" } },
  { name = "single:FIREBOMB", deck = { "FIREBOMB" } },
  { name = "single:SOILBALL", deck = { "SOILBALL" } },
  { name = "single:DEATH_CROSS", deck = { "DEATH_CROSS" } },
  { name = "single:DEATH_CROSS_BIG", deck = { "DEATH_CROSS_BIG" } },
  { name = "single:INFESTATION", deck = { "INFESTATION" } },
  { name = "single:WALL_HORIZONTAL", deck = { "WALL_HORIZONTAL" } },
  { name = "single:WALL_VERTICAL", deck = { "WALL_VERTICAL" } },
  { name = "single:WALL_SQUARE", deck = { "WALL_SQUARE" } },
  { name = "single:TEMPORARY_WALL", deck = { "TEMPORARY_WALL", "LIGHT_BULLET" } },
  { name = "single:TEMPORARY_PLATFORM", deck = { "TEMPORARY_PLATFORM", "LIGHT_BULLET" } },
  { name = "single:PURPLE_EXPLOSION_FIELD", deck = { "PURPLE_EXPLOSION_FIELD" } },
  { name = "single:DELAYED_SPELL", deck = { "DELAYED_SPELL" } },
  { name = "single:LONG_DISTANCE_CAST", deck = { "LONG_DISTANCE_CAST", "LIGHT_BULLET" } },
  { name = "single:TELEPORT_CAST", deck = { "TELEPORT_CAST", "LIGHT_BULLET" } },
  { name = "single:SUPER_TELEPORT_CAST", deck = { "SUPER_TELEPORT_CAST", "LIGHT_BULLET" } },
  { name = "single:CASTER_CAST", deck = { "CASTER_CAST", "LIGHT_BULLET" } },
  { name = "single:MIST_RADIOACTIVE", deck = { "MIST_RADIOACTIVE" } },
  { name = "single:MIST_ALCOHOL", deck = { "MIST_ALCOHOL" } },
  { name = "single:MIST_SLIME", deck = { "MIST_SLIME" } },
  { name = "single:MIST_BLOOD", deck = { "MIST_BLOOD" } },
  { name = "single:CIRCLE_FIRE", deck = { "CIRCLE_FIRE" } },
  { name = "single:CIRCLE_ACID", deck = { "CIRCLE_ACID" } },
  { name = "single:CIRCLE_OIL", deck = { "CIRCLE_OIL" } },
  { name = "single:CIRCLE_WATER", deck = { "CIRCLE_WATER" } },
  { name = "single:MATERIAL_WATER", deck = { "MATERIAL_WATER" } },
  { name = "single:MATERIAL_OIL", deck = { "MATERIAL_OIL" } },
  { name = "single:MATERIAL_BLOOD", deck = { "MATERIAL_BLOOD" } },
  { name = "single:MATERIAL_ACID", deck = { "MATERIAL_ACID" } },
  { name = "single:MATERIAL_CEMENT", deck = { "MATERIAL_CEMENT" } },
  { name = "single:TELEPORT_PROJECTILE", deck = { "TELEPORT_PROJECTILE" } },
  { name = "single:TELEPORT_PROJECTILE_SHORT", deck = { "TELEPORT_PROJECTILE_SHORT" } },
  { name = "single:TELEPORT_PROJECTILE_STATIC", deck = { "TELEPORT_PROJECTILE_STATIC" } },
  { name = "single:SWAPPER_PROJECTILE", deck = { "SWAPPER_PROJECTILE" } },
  { name = "single:TELEPORT_PROJECTILE_CLOSER", deck = { "TELEPORT_PROJECTILE_CLOSER" } },
  { name = "single:NUKE", deck = { "NUKE" } },
  { name = "single:NUKE_GIGA", deck = { "NUKE_GIGA" } },
  { name = "single:FIREWORK", deck = { "FIREWORK" } },
  { name = "single:SUMMON_WANDGHOST", deck = { "SUMMON_WANDGHOST", "LIGHT_BULLET" } },
  { name = "single:TOUCH_GOLD", deck = { "TOUCH_GOLD" } },
  { name = "single:TOUCH_WATER", deck = { "TOUCH_WATER" } },
  { name = "single:TOUCH_OIL", deck = { "TOUCH_OIL" } },
  { name = "single:TOUCH_ALCOHOL", deck = { "TOUCH_ALCOHOL" } },
  { name = "single:TOUCH_PISS", deck = { "TOUCH_PISS" } },
  { name = "single:TOUCH_GRASS", deck = { "TOUCH_GRASS" } },
  { name = "single:TOUCH_BLOOD", deck = { "TOUCH_BLOOD" } },
  { name = "single:TOUCH_SMOKE", deck = { "TOUCH_SMOKE" } },
  { name = "single:DESTRUCTION", deck = { "DESTRUCTION" } },
  { name = "single:MASS_POLYMORPH", deck = { "MASS_POLYMORPH" } },
  { name = "single:BURST_2", deck = { "BURST_2", "LIGHT_BULLET" } },
  { name = "single:BURST_3", deck = { "BURST_3", "LIGHT_BULLET" } },
  { name = "single:BURST_4", deck = { "BURST_4", "LIGHT_BULLET" } },
  { name = "single:BURST_8", deck = { "BURST_8", "LIGHT_BULLET" } },
  { name = "single:BURST_X", deck = { "BURST_X", "LIGHT_BULLET" } },
  { name = "single:SCATTER_2", deck = { "SCATTER_2", "LIGHT_BULLET" } },
  { name = "single:SCATTER_3", deck = { "SCATTER_3", "LIGHT_BULLET" } },
  { name = "single:SCATTER_4", deck = { "SCATTER_4", "LIGHT_BULLET" } },
  { name = "single:I_SHAPE", deck = { "I_SHAPE", "LIGHT_BULLET" } },
  { name = "single:Y_SHAPE", deck = { "Y_SHAPE", "LIGHT_BULLET" } },
  { name = "single:T_SHAPE", deck = { "T_SHAPE", "LIGHT_BULLET" } },
  { name = "single:W_SHAPE", deck = { "W_SHAPE", "LIGHT_BULLET" } },
  { name = "single:CIRCLE_SHAPE", deck = { "CIRCLE_SHAPE", "LIGHT_BULLET" } },
  { name = "single:PENTAGRAM_SHAPE", deck = { "PENTAGRAM_SHAPE", "LIGHT_BULLET" } },
  { name = "single:I_SHOT", deck = { "I_SHOT", "LIGHT_BULLET" } },
  { name = "single:Y_SHOT", deck = { "Y_SHOT", "LIGHT_BULLET" } },
  { name = "single:T_SHOT", deck = { "T_SHOT", "LIGHT_BULLET" } },
  { name = "single:W_SHOT", deck = { "W_SHOT", "LIGHT_BULLET" } },
  { name = "single:QUAD_SHOT", deck = { "QUAD_SHOT", "LIGHT_BULLET" } },
  { name = "single:PENTA_SHOT", deck = { "PENTA_SHOT", "LIGHT_BULLET" } },
  { name = "single:HEXA_SHOT", deck = { "HEXA_SHOT", "LIGHT_BULLET" } },
  { name = "single:SPREAD_REDUCE", deck = { "SPREAD_REDUCE", "LIGHT_BULLET" } },
  { name = "single:HEAVY_SPREAD", deck = { "HEAVY_SPREAD", "LIGHT_BULLET" } },
  { name = "single:RECHARGE", deck = { "RECHARGE", "LIGHT_BULLET" } },
  { name = "single:LIFETIME", deck = { "LIFETIME", "LIGHT_BULLET" } },
  { name = "single:LIFETIME_DOWN", deck = { "LIFETIME_DOWN", "LIGHT_BULLET" } },
  { name = "single:NOLLA", deck = { "NOLLA", "LIGHT_BULLET" } },
  { name = "single:SLOW_BUT_STEADY", deck = { "SLOW_BUT_STEADY", "LIGHT_BULLET" } },
  { name = "single:EXPLOSION_REMOVE", deck = { "EXPLOSION_REMOVE", "LIGHT_BULLET" } },
  { name = "single:EXPLOSION_TINY", deck = { "EXPLOSION_TINY", "LIGHT_BULLET" } },
  { name = "single:LASER_EMITTER_WIDER", deck = { "LASER_EMITTER_WIDER", "LIGHT_BULLET" } },
  { name = "single:MANA_REDUCE", deck = { "MANA_REDUCE", "LIGHT_BULLET" } },
  { name = "single:BLOOD_MAGIC", deck = { "BLOOD_MAGIC", "LIGHT_BULLET" } },
  { name = "single:MONEY_MAGIC", deck = { "MONEY_MAGIC", "LIGHT_BULLET" } },
  { name = "single:BLOOD_TO_POWER", deck = { "BLOOD_TO_POWER", "LIGHT_BULLET" } },
  { name = "single:DUPLICATE", deck = { "DUPLICATE", "LIGHT_BULLET" } },
  { name = "single:QUANTUM_SPLIT", deck = { "QUANTUM_SPLIT", "LIGHT_BULLET" } },
  { name = "single:GRAVITY", deck = { "GRAVITY", "LIGHT_BULLET" } },
  { name = "single:GRAVITY_ANTI", deck = { "GRAVITY_ANTI", "LIGHT_BULLET" } },
  { name = "single:SINEWAVE", deck = { "SINEWAVE", "LIGHT_BULLET" } },
  { name = "single:CHAOTIC_ARC", deck = { "CHAOTIC_ARC", "LIGHT_BULLET" } },
  { name = "single:PINGPONG_PATH", deck = { "PINGPONG_PATH", "LIGHT_BULLET" } },
  { name = "single:AVOIDING_ARC", deck = { "AVOIDING_ARC", "LIGHT_BULLET" } },
  { name = "single:FLOATING_ARC", deck = { "FLOATING_ARC", "LIGHT_BULLET" } },
  { name = "single:FLY_DOWNWARDS", deck = { "FLY_DOWNWARDS", "LIGHT_BULLET" } },
  { name = "single:FLY_UPWARDS", deck = { "FLY_UPWARDS", "LIGHT_BULLET" } },
  { name = "single:HORIZONTAL_ARC", deck = { "HORIZONTAL_ARC", "LIGHT_BULLET" } },
  { name = "single:LINE_ARC", deck = { "LINE_ARC", "LIGHT_BULLET" } },
  { name = "single:ORBIT_SHOT", deck = { "ORBIT_SHOT", "LIGHT_BULLET" } },
  { name = "single:SPIRALING_SHOT", deck = { "SPIRALING_SHOT", "LIGHT_BULLET" } },
  { name = "single:PHASING_ARC", deck = { "PHASING_ARC", "LIGHT_BULLET" } },
  { name = "single:TRUE_ORBIT", deck = { "TRUE_ORBIT", "LIGHT_BULLET" } },
  { name = "single:BOUNCE", deck = { "BOUNCE", "LIGHT_BULLET" } },
  { name = "single:REMOVE_BOUNCE", deck = { "REMOVE_BOUNCE", "LIGHT_BULLET" } },
  { name = "single:HOMING", deck = { "HOMING", "LIGHT_BULLET" } },
  { name = "single:ANTI_HOMING", deck = { "ANTI_HOMING", "LIGHT_BULLET" } },
  { name = "single:HOMING_WAND", deck = { "HOMING_WAND", "LIGHT_BULLET" } },
  { name = "single:HOMING_SHORT", deck = { "HOMING_SHORT", "LIGHT_BULLET" } },
  { name = "single:HOMING_ROTATE", deck = { "HOMING_ROTATE", "LIGHT_BULLET" } },
  { name = "single:HOMING_SHOOTER", deck = { "HOMING_SHOOTER", "LIGHT_BULLET" } },
  { name = "single:AUTOAIM", deck = { "AUTOAIM", "LIGHT_BULLET" } },
  { name = "single:HOMING_ACCELERATING", deck = { "HOMING_ACCELERATING", "LIGHT_BULLET" } },
  { name = "single:HOMING_CURSOR", deck = { "HOMING_CURSOR", "LIGHT_BULLET" } },
  { name = "single:HOMING_AREA", deck = { "HOMING_AREA", "LIGHT_BULLET" } },
  { name = "single:PIERCING_SHOT", deck = { "PIERCING_SHOT", "LIGHT_BULLET" } },
  { name = "single:CLIPPING_SHOT", deck = { "CLIPPING_SHOT", "LIGHT_BULLET" } },
  { name = "single:DAMAGE", deck = { "DAMAGE", "LIGHT_BULLET" } },
  { name = "single:DAMAGE_RANDOM", deck = { "DAMAGE_RANDOM", "LIGHT_BULLET" } },
  { name = "single:BLOODLUST", deck = { "BLOODLUST", "LIGHT_BULLET" } },
  { name = "single:DAMAGE_FOREVER", deck = { "DAMAGE_FOREVER", "LIGHT_BULLET" } },
  { name = "single:CRITICAL_HIT", deck = { "CRITICAL_HIT", "LIGHT_BULLET" } },
  { name = "single:AREA_DAMAGE", deck = { "AREA_DAMAGE", "LIGHT_BULLET" } },
  { name = "single:SPELLS_TO_POWER", deck = { "SPELLS_TO_POWER", "LIGHT_BULLET" } },
  { name = "single:ESSENCE_TO_POWER", deck = { "ESSENCE_TO_POWER", "LIGHT_BULLET" } },
  { name = "single:ZERO_DAMAGE", deck = { "ZERO_DAMAGE", "LIGHT_BULLET" } },
  { name = "single:HEAVY_SHOT", deck = { "HEAVY_SHOT", "LIGHT_BULLET" } },
  { name = "single:LIGHT_SHOT", deck = { "LIGHT_SHOT", "LIGHT_BULLET" } },
  { name = "single:KNOCKBACK", deck = { "KNOCKBACK", "LIGHT_BULLET" } },
  { name = "single:RECOIL", deck = { "RECOIL", "LIGHT_BULLET" } },
  { name = "single:RECOIL_DAMPER", deck = { "RECOIL_DAMPER", "LIGHT_BULLET" } },
  { name = "single:SPEED", deck = { "SPEED", "LIGHT_BULLET" } },
  { name = "single:ACCELERATING_SHOT", deck = { "ACCELERATING_SHOT", "LIGHT_BULLET" } },
  { name = "single:DECELERATING_SHOT", deck = { "DECELERATING_SHOT", "LIGHT_BULLET" } },
  { name = "single:EXPLOSIVE_PROJECTILE", deck = { "EXPLOSIVE_PROJECTILE", "LIGHT_BULLET" } },
  { name = "single:CLUSTERMOD", deck = { "CLUSTERMOD", "LIGHT_BULLET" } },
  { name = "single:WATER_TO_POISON", deck = { "WATER_TO_POISON", "LIGHT_BULLET" } },
  { name = "single:BLOOD_TO_ACID", deck = { "BLOOD_TO_ACID", "LIGHT_BULLET" } },
  { name = "single:LAVA_TO_BLOOD", deck = { "LAVA_TO_BLOOD", "LIGHT_BULLET" } },
  { name = "single:LIQUID_TO_EXPLOSION", deck = { "LIQUID_TO_EXPLOSION", "LIGHT_BULLET" } },
  { name = "single:TOXIC_TO_ACID", deck = { "TOXIC_TO_ACID", "LIGHT_BULLET" } },
  { name = "single:STATIC_TO_SAND", deck = { "STATIC_TO_SAND", "LIGHT_BULLET" } },
  { name = "single:TRANSMUTATION", deck = { "TRANSMUTATION", "LIGHT_BULLET" } },
  { name = "single:RANDOM_EXPLOSION", deck = { "RANDOM_EXPLOSION", "LIGHT_BULLET" } },
  { name = "single:NECROMANCY", deck = { "NECROMANCY", "LIGHT_BULLET" } },
  { name = "single:LIGHT", deck = { "LIGHT", "LIGHT_BULLET" } },
  { name = "single:EXPLOSION", deck = { "EXPLOSION" } },
  { name = "single:EXPLOSION_LIGHT", deck = { "EXPLOSION_LIGHT" } },
  { name = "single:FIRE_BLAST", deck = { "FIRE_BLAST" } },
  { name = "single:POISON_BLAST", deck = { "POISON_BLAST" } },
  { name = "single:ALCOHOL_BLAST", deck = { "ALCOHOL_BLAST" } },
  { name = "single:THUNDER_BLAST", deck = { "THUNDER_BLAST" } },
  { name = "single:BERSERK_FIELD", deck = { "BERSERK_FIELD" } },
  { name = "single:POLYMORPH_FIELD", deck = { "POLYMORPH_FIELD" } },
  { name = "single:CHAOS_POLYMORPH_FIELD", deck = { "CHAOS_POLYMORPH_FIELD" } },
  { name = "single:ELECTROCUTION_FIELD", deck = { "ELECTROCUTION_FIELD" } },
  { name = "single:FREEZE_FIELD", deck = { "FREEZE_FIELD" } },
  { name = "single:REGENERATION_FIELD", deck = { "REGENERATION_FIELD" } },
  { name = "single:TELEPORTATION_FIELD", deck = { "TELEPORTATION_FIELD" } },
  { name = "single:LEVITATION_FIELD", deck = { "LEVITATION_FIELD" } },
  { name = "single:SHIELD_FIELD", deck = { "SHIELD_FIELD" } },
  { name = "single:PROJECTILE_TRANSMUTATION_FIELD", deck = { "PROJECTILE_TRANSMUTATION_FIELD" } },
  { name = "single:PROJECTILE_THUNDER_FIELD", deck = { "PROJECTILE_THUNDER_FIELD" } },
  { name = "single:PROJECTILE_GRAVITY_FIELD", deck = { "PROJECTILE_GRAVITY_FIELD" } },
  { name = "single:VACUUM_POWDER", deck = { "VACUUM_POWDER" } },
  { name = "single:VACUUM_LIQUID", deck = { "VACUUM_LIQUID" } },
  { name = "single:VACUUM_ENTITIES", deck = { "VACUUM_ENTITIES" } },
  { name = "single:SEA_LAVA", deck = { "SEA_LAVA" } },
  { name = "single:SEA_ALCOHOL", deck = { "SEA_ALCOHOL" } },
  { name = "single:SEA_OIL", deck = { "SEA_OIL" } },
  { name = "single:SEA_WATER", deck = { "SEA_WATER" } },
  { name = "single:SEA_SWAMP", deck = { "SEA_SWAMP" } },
  { name = "single:SEA_ACID", deck = { "SEA_ACID" } },
  { name = "single:SEA_ACID_GAS", deck = { "SEA_ACID_GAS" } },
  { name = "single:SEA_MIMIC", deck = { "SEA_MIMIC" } },
  { name = "single:CLOUD_WATER", deck = { "CLOUD_WATER" } },
  { name = "single:CLOUD_OIL", deck = { "CLOUD_OIL" } },
  { name = "single:CLOUD_BLOOD", deck = { "CLOUD_BLOOD" } },
  { name = "single:CLOUD_ACID", deck = { "CLOUD_ACID" } },
  { name = "single:CLOUD_THUNDER", deck = { "CLOUD_THUNDER" } },
  { name = "single:ELECTRIC_CHARGE", deck = { "ELECTRIC_CHARGE", "LIGHT_BULLET" } },
  { name = "single:MATTER_EATER", deck = { "MATTER_EATER", "LIGHT_BULLET" } },
  { name = "single:FREEZE", deck = { "FREEZE", "LIGHT_BULLET" } },
  { name = "single:HITFX_BURNING_CRITICAL_HIT", deck = { "HITFX_BURNING_CRITICAL_HIT", "LIGHT_BULLET" } },
  { name = "single:HITFX_CRITICAL_WATER", deck = { "HITFX_CRITICAL_WATER", "LIGHT_BULLET" } },
  { name = "single:HITFX_CRITICAL_OIL", deck = { "HITFX_CRITICAL_OIL", "LIGHT_BULLET" } },
  { name = "single:HITFX_CRITICAL_BLOOD", deck = { "HITFX_CRITICAL_BLOOD", "LIGHT_BULLET" } },
  { name = "single:HITFX_TOXIC_CHARM", deck = { "HITFX_TOXIC_CHARM", "LIGHT_BULLET" } },
  { name = "single:HITFX_EXPLOSION_SLIME", deck = { "HITFX_EXPLOSION_SLIME", "LIGHT_BULLET" } },
  { name = "single:HITFX_EXPLOSION_SLIME_GIGA", deck = { "HITFX_EXPLOSION_SLIME_GIGA", "LIGHT_BULLET" } },
  { name = "single:HITFX_EXPLOSION_ALCOHOL", deck = { "HITFX_EXPLOSION_ALCOHOL", "LIGHT_BULLET" } },
  { name = "single:HITFX_EXPLOSION_ALCOHOL_GIGA", deck = { "HITFX_EXPLOSION_ALCOHOL_GIGA", "LIGHT_BULLET" } },
  { name = "single:HITFX_PETRIFY", deck = { "HITFX_PETRIFY", "LIGHT_BULLET" } },
  { name = "single:ROCKET_DOWNWARDS", deck = { "ROCKET_DOWNWARDS", "LIGHT_BULLET" } },
  { name = "single:ROCKET_OCTAGON", deck = { "ROCKET_OCTAGON", "LIGHT_BULLET" } },
  { name = "single:FIZZLE", deck = { "FIZZLE", "LIGHT_BULLET" } },
  { name = "single:BOUNCE_EXPLOSION", deck = { "BOUNCE_EXPLOSION", "LIGHT_BULLET" } },
  { name = "single:BOUNCE_SPARK", deck = { "BOUNCE_SPARK", "LIGHT_BULLET" } },
  { name = "single:BOUNCE_LASER", deck = { "BOUNCE_LASER", "LIGHT_BULLET" } },
  { name = "single:BOUNCE_LASER_EMITTER", deck = { "BOUNCE_LASER_EMITTER", "LIGHT_BULLET" } },
  { name = "single:BOUNCE_LARPA", deck = { "BOUNCE_LARPA", "LIGHT_BULLET" } },
  { name = "single:BOUNCE_SMALL_EXPLOSION", deck = { "BOUNCE_SMALL_EXPLOSION", "LIGHT_BULLET" } },
  { name = "single:BOUNCE_LIGHTNING", deck = { "BOUNCE_LIGHTNING", "LIGHT_BULLET" } },
  { name = "single:BOUNCE_HOLE", deck = { "BOUNCE_HOLE", "LIGHT_BULLET" } },
  { name = "single:FIREBALL_RAY", deck = { "FIREBALL_RAY", "LIGHT_BULLET" } },
  { name = "single:LIGHTNING_RAY", deck = { "LIGHTNING_RAY", "LIGHT_BULLET" } },
  { name = "single:TENTACLE_RAY", deck = { "TENTACLE_RAY", "LIGHT_BULLET" } },
  { name = "single:LASER_EMITTER_RAY", deck = { "LASER_EMITTER_RAY", "LIGHT_BULLET" } },
  { name = "single:FIREBALL_RAY_LINE", deck = { "FIREBALL_RAY_LINE", "LIGHT_BULLET" } },
  { name = "single:FIREBALL_RAY_ENEMY", deck = { "FIREBALL_RAY_ENEMY", "LIGHT_BULLET" } },
  { name = "single:LIGHTNING_RAY_ENEMY", deck = { "LIGHTNING_RAY_ENEMY", "LIGHT_BULLET" } },
  { name = "single:TENTACLE_RAY_ENEMY", deck = { "TENTACLE_RAY_ENEMY", "LIGHT_BULLET" } },
  { name = "single:GRAVITY_FIELD_ENEMY", deck = { "GRAVITY_FIELD_ENEMY", "LIGHT_BULLET" } },
  { name = "single:CURSE", deck = { "CURSE", "LIGHT_BULLET" } },
  { name = "single:CURSE_WITHER_PROJECTILE", deck = { "CURSE_WITHER_PROJECTILE", "LIGHT_BULLET" } },
  { name = "single:CURSE_WITHER_EXPLOSION", deck = { "CURSE_WITHER_EXPLOSION", "LIGHT_BULLET" } },
  { name = "single:CURSE_WITHER_MELEE", deck = { "CURSE_WITHER_MELEE", "LIGHT_BULLET" } },
  { name = "single:CURSE_WITHER_ELECTRICITY", deck = { "CURSE_WITHER_ELECTRICITY", "LIGHT_BULLET" } },
  { name = "single:ORBIT_DISCS", deck = { "ORBIT_DISCS", "LIGHT_BULLET" } },
  { name = "single:ORBIT_FIREBALLS", deck = { "ORBIT_FIREBALLS", "LIGHT_BULLET" } },
  { name = "single:ORBIT_NUKES", deck = { "ORBIT_NUKES", "LIGHT_BULLET" } },
  { name = "single:ORBIT_LASERS", deck = { "ORBIT_LASERS", "LIGHT_BULLET" } },
  { name = "single:ORBIT_LARPA", deck = { "ORBIT_LARPA", "LIGHT_BULLET" } },
  { name = "single:CHAIN_SHOT", deck = { "CHAIN_SHOT", "LIGHT_BULLET" } },
  { name = "single:ARC_ELECTRIC", deck = { "ARC_ELECTRIC", "LIGHT_BULLET" } },
  { name = "single:ARC_FIRE", deck = { "ARC_FIRE", "LIGHT_BULLET" } },
  { name = "single:ARC_GUNPOWDER", deck = { "ARC_GUNPOWDER", "LIGHT_BULLET" } },
  { name = "single:ARC_POISON", deck = { "ARC_POISON", "LIGHT_BULLET" } },
  { name = "single:CRUMBLING_EARTH_PROJECTILE", deck = { "CRUMBLING_EARTH_PROJECTILE", "LIGHT_BULLET" } },
  { name = "single:X_RAY", deck = { "X_RAY", "LIGHT_BULLET" } },
  { name = "single:UNSTABLE_GUNPOWDER", deck = { "UNSTABLE_GUNPOWDER", "LIGHT_BULLET" } },
  { name = "single:ACID_TRAIL", deck = { "ACID_TRAIL", "LIGHT_BULLET" } },
  { name = "single:POISON_TRAIL", deck = { "POISON_TRAIL", "LIGHT_BULLET" } },
  { name = "single:OIL_TRAIL", deck = { "OIL_TRAIL", "LIGHT_BULLET" } },
  { name = "single:WATER_TRAIL", deck = { "WATER_TRAIL", "LIGHT_BULLET" } },
  { name = "single:GUNPOWDER_TRAIL", deck = { "GUNPOWDER_TRAIL", "LIGHT_BULLET" } },
  { name = "single:FIRE_TRAIL", deck = { "FIRE_TRAIL", "LIGHT_BULLET" } },
  { name = "single:BURN_TRAIL", deck = { "BURN_TRAIL", "LIGHT_BULLET" } },
  { name = "single:TORCH", deck = { "TORCH", "LIGHT_BULLET" } },
  { name = "single:TORCH_ELECTRIC", deck = { "TORCH_ELECTRIC", "LIGHT_BULLET" } },
  { name = "single:ENERGY_SHIELD", deck = { "ENERGY_SHIELD", "LIGHT_BULLET" } },
  { name = "single:ENERGY_SHIELD_SECTOR", deck = { "ENERGY_SHIELD_SECTOR", "LIGHT_BULLET" } },
  { name = "single:ENERGY_SHIELD_SHOT", deck = { "ENERGY_SHIELD_SHOT", "LIGHT_BULLET" } },
  { name = "single:TINY_GHOST", deck = { "TINY_GHOST", "LIGHT_BULLET" } },
  { name = "single:OCARINA_A", deck = { "OCARINA_A", "LIGHT_BULLET" } },
  { name = "single:OCARINA_B", deck = { "OCARINA_B", "LIGHT_BULLET" } },
  { name = "single:OCARINA_C", deck = { "OCARINA_C", "LIGHT_BULLET" } },
  { name = "single:OCARINA_D", deck = { "OCARINA_D", "LIGHT_BULLET" } },
  { name = "single:OCARINA_E", deck = { "OCARINA_E", "LIGHT_BULLET" } },
  { name = "single:OCARINA_F", deck = { "OCARINA_F", "LIGHT_BULLET" } },
  { name = "single:OCARINA_GSHARP", deck = { "OCARINA_GSHARP", "LIGHT_BULLET" } },
  { name = "single:OCARINA_A2", deck = { "OCARINA_A2", "LIGHT_BULLET" } },
  { name = "single:KANTELE_A", deck = { "KANTELE_A", "LIGHT_BULLET" } },
  { name = "single:KANTELE_D", deck = { "KANTELE_D", "LIGHT_BULLET" } },
  { name = "single:KANTELE_DIS", deck = { "KANTELE_DIS", "LIGHT_BULLET" } },
  { name = "single:KANTELE_E", deck = { "KANTELE_E", "LIGHT_BULLET" } },
  { name = "single:KANTELE_G", deck = { "KANTELE_G", "LIGHT_BULLET" } },
  { name = "single:RANDOM_SPELL", deck = { "RANDOM_SPELL", "LIGHT_BULLET" } },
  { name = "single:RANDOM_PROJECTILE", deck = { "RANDOM_PROJECTILE" } },
  { name = "single:RANDOM_MODIFIER", deck = { "RANDOM_MODIFIER", "LIGHT_BULLET" } },
  { name = "single:RANDOM_STATIC_PROJECTILE", deck = { "RANDOM_STATIC_PROJECTILE" } },
  { name = "single:DRAW_RANDOM", deck = { "DRAW_RANDOM", "LIGHT_BULLET" } },
  { name = "single:DRAW_RANDOM_X3", deck = { "DRAW_RANDOM_X3", "LIGHT_BULLET" } },
  { name = "single:DRAW_3_RANDOM", deck = { "DRAW_3_RANDOM", "LIGHT_BULLET" } },
  { name = "single:ALL_NUKES", deck = { "ALL_NUKES", "LIGHT_BULLET" } },
  { name = "single:ALL_DISCS", deck = { "ALL_DISCS", "LIGHT_BULLET" } },
  { name = "single:ALL_ROCKETS", deck = { "ALL_ROCKETS", "LIGHT_BULLET" } },
  { name = "single:ALL_DEATHCROSSES", deck = { "ALL_DEATHCROSSES", "LIGHT_BULLET" } },
  { name = "single:ALL_BLACKHOLES", deck = { "ALL_BLACKHOLES", "LIGHT_BULLET" } },
  { name = "single:ALL_ACID", deck = { "ALL_ACID", "LIGHT_BULLET" } },
  { name = "single:ALL_SPELLS", deck = { "ALL_SPELLS", "LIGHT_BULLET" } },
  { name = "single:SUMMON_PORTAL", deck = { "SUMMON_PORTAL", "LIGHT_BULLET" } },
  { name = "single:ADD_TRIGGER", deck = { "ADD_TRIGGER", "LIGHT_BULLET" } },
  { name = "single:ADD_TIMER", deck = { "ADD_TIMER", "LIGHT_BULLET" } },
  { name = "single:ADD_DEATH_TRIGGER", deck = { "ADD_DEATH_TRIGGER", "LIGHT_BULLET" } },
  { name = "single:LARPA_CHAOS", deck = { "LARPA_CHAOS", "LIGHT_BULLET" } },
  { name = "single:LARPA_DOWNWARDS", deck = { "LARPA_DOWNWARDS", "LIGHT_BULLET" } },
  { name = "single:LARPA_UPWARDS", deck = { "LARPA_UPWARDS", "LIGHT_BULLET" } },
  { name = "single:LARPA_CHAOS_2", deck = { "LARPA_CHAOS_2", "LIGHT_BULLET" } },
  { name = "single:LARPA_DEATH", deck = { "LARPA_DEATH", "LIGHT_BULLET" } },
  { name = "single:ALPHA", deck = { "ALPHA", "LIGHT_BULLET" } },
  { name = "single:GAMMA", deck = { "GAMMA", "LIGHT_BULLET" } },
  { name = "single:TAU", deck = { "TAU", "LIGHT_BULLET" } },
  { name = "single:OMEGA", deck = { "OMEGA", "LIGHT_BULLET" } },
  { name = "single:MU", deck = { "MU", "LIGHT_BULLET" } },
  { name = "single:PHI", deck = { "PHI", "LIGHT_BULLET" } },
  { name = "single:SIGMA", deck = { "SIGMA", "LIGHT_BULLET" } },
  { name = "single:ZETA", deck = { "ZETA", "LIGHT_BULLET" } },
  { name = "single:DIVIDE_2", deck = { "DIVIDE_2", "LIGHT_BULLET" } },
  { name = "single:DIVIDE_3", deck = { "DIVIDE_3", "LIGHT_BULLET" } },
  { name = "single:DIVIDE_4", deck = { "DIVIDE_4", "LIGHT_BULLET" } },
  { name = "single:DIVIDE_10", deck = { "DIVIDE_10", "LIGHT_BULLET" } },
  { name = "single:METEOR_RAIN", deck = { "METEOR_RAIN" } },
  { name = "single:WORM_RAIN", deck = { "WORM_RAIN" } },
  { name = "single:RESET", deck = { "RESET", "LIGHT_BULLET" } },
  { name = "single:IF_ENEMY", deck = { "IF_ENEMY", "LIGHT_BULLET" } },
  { name = "single:IF_PROJECTILE", deck = { "IF_PROJECTILE", "LIGHT_BULLET" } },
  { name = "single:IF_HP", deck = { "IF_HP", "LIGHT_BULLET" } },
  { name = "single:IF_HALF", deck = { "IF_HALF", "LIGHT_BULLET" } },
  { name = "single:IF_END", deck = { "IF_END", "LIGHT_BULLET" } },
  { name = "single:IF_ELSE", deck = { "IF_ELSE", "LIGHT_BULLET" } },
  { name = "single:COLOUR_RED", deck = { "COLOUR_RED", "LIGHT_BULLET" } },
  { name = "single:COLOUR_ORANGE", deck = { "COLOUR_ORANGE", "LIGHT_BULLET" } },
  { name = "single:COLOUR_GREEN", deck = { "COLOUR_GREEN", "LIGHT_BULLET" } },
  { name = "single:COLOUR_YELLOW", deck = { "COLOUR_YELLOW", "LIGHT_BULLET" } },
  { name = "single:COLOUR_PURPLE", deck = { "COLOUR_PURPLE", "LIGHT_BULLET" } },
  { name = "single:COLOUR_BLUE", deck = { "COLOUR_BLUE", "LIGHT_BULLET" } },
  { name = "single:COLOUR_RAINBOW", deck = { "COLOUR_RAINBOW", "LIGHT_BULLET" } },
  { name = "single:COLOUR_INVIS", deck = { "COLOUR_INVIS", "LIGHT_BULLET" } },
  { name = "single:RAINBOW_TRAIL", deck = { "RAINBOW_TRAIL", "LIGHT_BULLET" } },
  { name = "single:CESSATION", deck = { "CESSATION", "LIGHT_BULLET" } },
  { name = "mod:SPREAD_REDUCE+LIGHT_BULLET", deck = { "SPREAD_REDUCE", "LIGHT_BULLET" } },
  { name = "mod:SPREAD_REDUCE+BOUNCY_ORB", deck = { "SPREAD_REDUCE", "BOUNCY_ORB" } },
  { name = "mod:SPREAD_REDUCE+GRENADE", deck = { "SPREAD_REDUCE", "GRENADE" } },
  { name = "mod:HEAVY_SPREAD+LIGHT_BULLET", deck = { "HEAVY_SPREAD", "LIGHT_BULLET" } },
  { name = "mod:HEAVY_SPREAD+BOUNCY_ORB", deck = { "HEAVY_SPREAD", "BOUNCY_ORB" } },
  { name = "mod:HEAVY_SPREAD+GRENADE", deck = { "HEAVY_SPREAD", "GRENADE" } },
  { name = "mod:RECHARGE+LIGHT_BULLET", deck = { "RECHARGE", "LIGHT_BULLET" } },
  { name = "mod:RECHARGE+BOUNCY_ORB", deck = { "RECHARGE", "BOUNCY_ORB" } },
  { name = "mod:RECHARGE+GRENADE", deck = { "RECHARGE", "GRENADE" } },
  { name = "mod:LIFETIME+LIGHT_BULLET", deck = { "LIFETIME", "LIGHT_BULLET" } },
  { name = "mod:LIFETIME+BOUNCY_ORB", deck = { "LIFETIME", "BOUNCY_ORB" } },
  { name = "mod:LIFETIME+GRENADE", deck = { "LIFETIME", "GRENADE" } },
  { name = "mod:LIFETIME_DOWN+LIGHT_BULLET", deck = { "LIFETIME_DOWN", "LIGHT_BULLET" } },
  { name = "mod:LIFETIME_DOWN+BOUNCY_ORB", deck = { "LIFETIME_DOWN", "BOUNCY_ORB" } },
  { name = "mod:LIFETIME_DOWN+GRENADE", deck = { "LIFETIME_DOWN", "GRENADE" } },
  { name = "mod:NOLLA+LIGHT_BULLET", deck = { "NOLLA", "LIGHT_BULLET" } },
  { name = "mod:NOLLA+BOUNCY_ORB", deck = { "NOLLA", "BOUNCY_ORB" } },
  { name = "mod:NOLLA+GRENADE", deck = { "NOLLA", "GRENADE" } },
  { name = "mod:SLOW_BUT_STEADY+LIGHT_BULLET", deck = { "SLOW_BUT_STEADY", "LIGHT_BULLET" } },
  { name = "mod:SLOW_BUT_STEADY+BOUNCY_ORB", deck = { "SLOW_BUT_STEADY", "BOUNCY_ORB" } },
  { name = "mod:SLOW_BUT_STEADY+GRENADE", deck = { "SLOW_BUT_STEADY", "GRENADE" } },
  { name = "mod:EXPLOSION_REMOVE+LIGHT_BULLET", deck = { "EXPLOSION_REMOVE", "LIGHT_BULLET" } },
  { name = "mod:EXPLOSION_REMOVE+BOUNCY_ORB", deck = { "EXPLOSION_REMOVE", "BOUNCY_ORB" } },
  { name = "mod:EXPLOSION_REMOVE+GRENADE", deck = { "EXPLOSION_REMOVE", "GRENADE" } },
  { name = "mod:EXPLOSION_TINY+LIGHT_BULLET", deck = { "EXPLOSION_TINY", "LIGHT_BULLET" } },
  { name = "mod:EXPLOSION_TINY+BOUNCY_ORB", deck = { "EXPLOSION_TINY", "BOUNCY_ORB" } },
  { name = "mod:EXPLOSION_TINY+GRENADE", deck = { "EXPLOSION_TINY", "GRENADE" } },
  { name = "mod:LASER_EMITTER_WIDER+LIGHT_BULLET", deck = { "LASER_EMITTER_WIDER", "LIGHT_BULLET" } },
  { name = "mod:LASER_EMITTER_WIDER+BOUNCY_ORB", deck = { "LASER_EMITTER_WIDER", "BOUNCY_ORB" } },
  { name = "mod:LASER_EMITTER_WIDER+GRENADE", deck = { "LASER_EMITTER_WIDER", "GRENADE" } },
  { name = "mod:MANA_REDUCE+LIGHT_BULLET", deck = { "MANA_REDUCE", "LIGHT_BULLET" } },
  { name = "mod:MANA_REDUCE+BOUNCY_ORB", deck = { "MANA_REDUCE", "BOUNCY_ORB" } },
  { name = "mod:MANA_REDUCE+GRENADE", deck = { "MANA_REDUCE", "GRENADE" } },
  { name = "mod:QUANTUM_SPLIT+LIGHT_BULLET", deck = { "QUANTUM_SPLIT", "LIGHT_BULLET" } },
  { name = "mod:QUANTUM_SPLIT+BOUNCY_ORB", deck = { "QUANTUM_SPLIT", "BOUNCY_ORB" } },
  { name = "mod:QUANTUM_SPLIT+GRENADE", deck = { "QUANTUM_SPLIT", "GRENADE" } },
  { name = "mod:GRAVITY+LIGHT_BULLET", deck = { "GRAVITY", "LIGHT_BULLET" } },
  { name = "mod:GRAVITY+BOUNCY_ORB", deck = { "GRAVITY", "BOUNCY_ORB" } },
  { name = "mod:GRAVITY+GRENADE", deck = { "GRAVITY", "GRENADE" } },
  { name = "mod:GRAVITY_ANTI+LIGHT_BULLET", deck = { "GRAVITY_ANTI", "LIGHT_BULLET" } },
  { name = "mod:GRAVITY_ANTI+BOUNCY_ORB", deck = { "GRAVITY_ANTI", "BOUNCY_ORB" } },
  { name = "mod:GRAVITY_ANTI+GRENADE", deck = { "GRAVITY_ANTI", "GRENADE" } },
  { name = "mod:SINEWAVE+LIGHT_BULLET", deck = { "SINEWAVE", "LIGHT_BULLET" } },
  { name = "mod:SINEWAVE+BOUNCY_ORB", deck = { "SINEWAVE", "BOUNCY_ORB" } },
  { name = "mod:SINEWAVE+GRENADE", deck = { "SINEWAVE", "GRENADE" } },
  { name = "mod:CHAOTIC_ARC+LIGHT_BULLET", deck = { "CHAOTIC_ARC", "LIGHT_BULLET" } },
  { name = "mod:CHAOTIC_ARC+BOUNCY_ORB", deck = { "CHAOTIC_ARC", "BOUNCY_ORB" } },
  { name = "mod:CHAOTIC_ARC+GRENADE", deck = { "CHAOTIC_ARC", "GRENADE" } },
  { name = "mod:PINGPONG_PATH+LIGHT_BULLET", deck = { "PINGPONG_PATH", "LIGHT_BULLET" } },
  { name = "mod:PINGPONG_PATH+BOUNCY_ORB", deck = { "PINGPONG_PATH", "BOUNCY_ORB" } },
  { name = "mod:PINGPONG_PATH+GRENADE", deck = { "PINGPONG_PATH", "GRENADE" } },
  { name = "mod:AVOIDING_ARC+LIGHT_BULLET", deck = { "AVOIDING_ARC", "LIGHT_BULLET" } },
  { name = "mod:AVOIDING_ARC+BOUNCY_ORB", deck = { "AVOIDING_ARC", "BOUNCY_ORB" } },
  { name = "mod:AVOIDING_ARC+GRENADE", deck = { "AVOIDING_ARC", "GRENADE" } },
  { name = "mod:FLOATING_ARC+LIGHT_BULLET", deck = { "FLOATING_ARC", "LIGHT_BULLET" } },
  { name = "mod:FLOATING_ARC+BOUNCY_ORB", deck = { "FLOATING_ARC", "BOUNCY_ORB" } },
  { name = "mod:FLOATING_ARC+GRENADE", deck = { "FLOATING_ARC", "GRENADE" } },
  { name = "mod:FLY_DOWNWARDS+LIGHT_BULLET", deck = { "FLY_DOWNWARDS", "LIGHT_BULLET" } },
  { name = "mod:FLY_DOWNWARDS+BOUNCY_ORB", deck = { "FLY_DOWNWARDS", "BOUNCY_ORB" } },
  { name = "mod:FLY_DOWNWARDS+GRENADE", deck = { "FLY_DOWNWARDS", "GRENADE" } },
  { name = "mod:FLY_UPWARDS+LIGHT_BULLET", deck = { "FLY_UPWARDS", "LIGHT_BULLET" } },
  { name = "mod:FLY_UPWARDS+BOUNCY_ORB", deck = { "FLY_UPWARDS", "BOUNCY_ORB" } },
  { name = "mod:FLY_UPWARDS+GRENADE", deck = { "FLY_UPWARDS", "GRENADE" } },
  { name = "mod:HORIZONTAL_ARC+LIGHT_BULLET", deck = { "HORIZONTAL_ARC", "LIGHT_BULLET" } },
  { name = "mod:HORIZONTAL_ARC+BOUNCY_ORB", deck = { "HORIZONTAL_ARC", "BOUNCY_ORB" } },
  { name = "mod:HORIZONTAL_ARC+GRENADE", deck = { "HORIZONTAL_ARC", "GRENADE" } },
  { name = "mod:LINE_ARC+LIGHT_BULLET", deck = { "LINE_ARC", "LIGHT_BULLET" } },
  { name = "mod:LINE_ARC+BOUNCY_ORB", deck = { "LINE_ARC", "BOUNCY_ORB" } },
  { name = "mod:LINE_ARC+GRENADE", deck = { "LINE_ARC", "GRENADE" } },
  { name = "mod:ORBIT_SHOT+LIGHT_BULLET", deck = { "ORBIT_SHOT", "LIGHT_BULLET" } },
  { name = "mod:ORBIT_SHOT+BOUNCY_ORB", deck = { "ORBIT_SHOT", "BOUNCY_ORB" } },
  { name = "mod:ORBIT_SHOT+GRENADE", deck = { "ORBIT_SHOT", "GRENADE" } },
  { name = "mod:SPIRALING_SHOT+LIGHT_BULLET", deck = { "SPIRALING_SHOT", "LIGHT_BULLET" } },
  { name = "mod:SPIRALING_SHOT+BOUNCY_ORB", deck = { "SPIRALING_SHOT", "BOUNCY_ORB" } },
  { name = "mod:SPIRALING_SHOT+GRENADE", deck = { "SPIRALING_SHOT", "GRENADE" } },
  { name = "mod:PHASING_ARC+LIGHT_BULLET", deck = { "PHASING_ARC", "LIGHT_BULLET" } },
  { name = "mod:PHASING_ARC+BOUNCY_ORB", deck = { "PHASING_ARC", "BOUNCY_ORB" } },
  { name = "mod:PHASING_ARC+GRENADE", deck = { "PHASING_ARC", "GRENADE" } },
  { name = "mod:TRUE_ORBIT+LIGHT_BULLET", deck = { "TRUE_ORBIT", "LIGHT_BULLET" } },
  { name = "mod:TRUE_ORBIT+BOUNCY_ORB", deck = { "TRUE_ORBIT", "BOUNCY_ORB" } },
  { name = "mod:TRUE_ORBIT+GRENADE", deck = { "TRUE_ORBIT", "GRENADE" } },
  { name = "mod:BOUNCE+LIGHT_BULLET", deck = { "BOUNCE", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE+BOUNCY_ORB", deck = { "BOUNCE", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE+GRENADE", deck = { "BOUNCE", "GRENADE" } },
  { name = "mod:REMOVE_BOUNCE+LIGHT_BULLET", deck = { "REMOVE_BOUNCE", "LIGHT_BULLET" } },
  { name = "mod:REMOVE_BOUNCE+BOUNCY_ORB", deck = { "REMOVE_BOUNCE", "BOUNCY_ORB" } },
  { name = "mod:REMOVE_BOUNCE+GRENADE", deck = { "REMOVE_BOUNCE", "GRENADE" } },
  { name = "mod:HOMING+LIGHT_BULLET", deck = { "HOMING", "LIGHT_BULLET" } },
  { name = "mod:HOMING+BOUNCY_ORB", deck = { "HOMING", "BOUNCY_ORB" } },
  { name = "mod:HOMING+GRENADE", deck = { "HOMING", "GRENADE" } },
  { name = "mod:ANTI_HOMING+LIGHT_BULLET", deck = { "ANTI_HOMING", "LIGHT_BULLET" } },
  { name = "mod:ANTI_HOMING+BOUNCY_ORB", deck = { "ANTI_HOMING", "BOUNCY_ORB" } },
  { name = "mod:ANTI_HOMING+GRENADE", deck = { "ANTI_HOMING", "GRENADE" } },
  { name = "mod:HOMING_WAND+LIGHT_BULLET", deck = { "HOMING_WAND", "LIGHT_BULLET" } },
  { name = "mod:HOMING_WAND+BOUNCY_ORB", deck = { "HOMING_WAND", "BOUNCY_ORB" } },
  { name = "mod:HOMING_WAND+GRENADE", deck = { "HOMING_WAND", "GRENADE" } },
  { name = "mod:HOMING_SHORT+LIGHT_BULLET", deck = { "HOMING_SHORT", "LIGHT_BULLET" } },
  { name = "mod:HOMING_SHORT+BOUNCY_ORB", deck = { "HOMING_SHORT", "BOUNCY_ORB" } },
  { name = "mod:HOMING_SHORT+GRENADE", deck = { "HOMING_SHORT", "GRENADE" } },
  { name = "mod:HOMING_ROTATE+LIGHT_BULLET", deck = { "HOMING_ROTATE", "LIGHT_BULLET" } },
  { name = "mod:HOMING_ROTATE+BOUNCY_ORB", deck = { "HOMING_ROTATE", "BOUNCY_ORB" } },
  { name = "mod:HOMING_ROTATE+GRENADE", deck = { "HOMING_ROTATE", "GRENADE" } },
  { name = "mod:HOMING_SHOOTER+LIGHT_BULLET", deck = { "HOMING_SHOOTER", "LIGHT_BULLET" } },
  { name = "mod:HOMING_SHOOTER+BOUNCY_ORB", deck = { "HOMING_SHOOTER", "BOUNCY_ORB" } },
  { name = "mod:HOMING_SHOOTER+GRENADE", deck = { "HOMING_SHOOTER", "GRENADE" } },
  { name = "mod:AUTOAIM+LIGHT_BULLET", deck = { "AUTOAIM", "LIGHT_BULLET" } },
  { name = "mod:AUTOAIM+BOUNCY_ORB", deck = { "AUTOAIM", "BOUNCY_ORB" } },
  { name = "mod:AUTOAIM+GRENADE", deck = { "AUTOAIM", "GRENADE" } },
  { name = "mod:HOMING_ACCELERATING+LIGHT_BULLET", deck = { "HOMING_ACCELERATING", "LIGHT_BULLET" } },
  { name = "mod:HOMING_ACCELERATING+BOUNCY_ORB", deck = { "HOMING_ACCELERATING", "BOUNCY_ORB" } },
  { name = "mod:HOMING_ACCELERATING+GRENADE", deck = { "HOMING_ACCELERATING", "GRENADE" } },
  { name = "mod:HOMING_CURSOR+LIGHT_BULLET", deck = { "HOMING_CURSOR", "LIGHT_BULLET" } },
  { name = "mod:HOMING_CURSOR+BOUNCY_ORB", deck = { "HOMING_CURSOR", "BOUNCY_ORB" } },
  { name = "mod:HOMING_CURSOR+GRENADE", deck = { "HOMING_CURSOR", "GRENADE" } },
  { name = "mod:HOMING_AREA+LIGHT_BULLET", deck = { "HOMING_AREA", "LIGHT_BULLET" } },
  { name = "mod:HOMING_AREA+BOUNCY_ORB", deck = { "HOMING_AREA", "BOUNCY_ORB" } },
  { name = "mod:HOMING_AREA+GRENADE", deck = { "HOMING_AREA", "GRENADE" } },
  { name = "mod:PIERCING_SHOT+LIGHT_BULLET", deck = { "PIERCING_SHOT", "LIGHT_BULLET" } },
  { name = "mod:PIERCING_SHOT+BOUNCY_ORB", deck = { "PIERCING_SHOT", "BOUNCY_ORB" } },
  { name = "mod:PIERCING_SHOT+GRENADE", deck = { "PIERCING_SHOT", "GRENADE" } },
  { name = "mod:CLIPPING_SHOT+LIGHT_BULLET", deck = { "CLIPPING_SHOT", "LIGHT_BULLET" } },
  { name = "mod:CLIPPING_SHOT+BOUNCY_ORB", deck = { "CLIPPING_SHOT", "BOUNCY_ORB" } },
  { name = "mod:CLIPPING_SHOT+GRENADE", deck = { "CLIPPING_SHOT", "GRENADE" } },
  { name = "mod:DAMAGE+LIGHT_BULLET", deck = { "DAMAGE", "LIGHT_BULLET" } },
  { name = "mod:DAMAGE+BOUNCY_ORB", deck = { "DAMAGE", "BOUNCY_ORB" } },
  { name = "mod:DAMAGE+GRENADE", deck = { "DAMAGE", "GRENADE" } },
  { name = "mod:DAMAGE_RANDOM+LIGHT_BULLET", deck = { "DAMAGE_RANDOM", "LIGHT_BULLET" } },
  { name = "mod:DAMAGE_RANDOM+BOUNCY_ORB", deck = { "DAMAGE_RANDOM", "BOUNCY_ORB" } },
  { name = "mod:DAMAGE_RANDOM+GRENADE", deck = { "DAMAGE_RANDOM", "GRENADE" } },
  { name = "mod:BLOODLUST+LIGHT_BULLET", deck = { "BLOODLUST", "LIGHT_BULLET" } },
  { name = "mod:BLOODLUST+BOUNCY_ORB", deck = { "BLOODLUST", "BOUNCY_ORB" } },
  { name = "mod:BLOODLUST+GRENADE", deck = { "BLOODLUST", "GRENADE" } },
  { name = "mod:DAMAGE_FOREVER+LIGHT_BULLET", deck = { "DAMAGE_FOREVER", "LIGHT_BULLET" } },
  { name = "mod:DAMAGE_FOREVER+BOUNCY_ORB", deck = { "DAMAGE_FOREVER", "BOUNCY_ORB" } },
  { name = "mod:DAMAGE_FOREVER+GRENADE", deck = { "DAMAGE_FOREVER", "GRENADE" } },
  { name = "mod:CRITICAL_HIT+LIGHT_BULLET", deck = { "CRITICAL_HIT", "LIGHT_BULLET" } },
  { name = "mod:CRITICAL_HIT+BOUNCY_ORB", deck = { "CRITICAL_HIT", "BOUNCY_ORB" } },
  { name = "mod:CRITICAL_HIT+GRENADE", deck = { "CRITICAL_HIT", "GRENADE" } },
  { name = "mod:AREA_DAMAGE+LIGHT_BULLET", deck = { "AREA_DAMAGE", "LIGHT_BULLET" } },
  { name = "mod:AREA_DAMAGE+BOUNCY_ORB", deck = { "AREA_DAMAGE", "BOUNCY_ORB" } },
  { name = "mod:AREA_DAMAGE+GRENADE", deck = { "AREA_DAMAGE", "GRENADE" } },
  { name = "mod:SPELLS_TO_POWER+LIGHT_BULLET", deck = { "SPELLS_TO_POWER", "LIGHT_BULLET" } },
  { name = "mod:SPELLS_TO_POWER+BOUNCY_ORB", deck = { "SPELLS_TO_POWER", "BOUNCY_ORB" } },
  { name = "mod:SPELLS_TO_POWER+GRENADE", deck = { "SPELLS_TO_POWER", "GRENADE" } },
  { name = "mod:ESSENCE_TO_POWER+LIGHT_BULLET", deck = { "ESSENCE_TO_POWER", "LIGHT_BULLET" } },
  { name = "mod:ESSENCE_TO_POWER+BOUNCY_ORB", deck = { "ESSENCE_TO_POWER", "BOUNCY_ORB" } },
  { name = "mod:ESSENCE_TO_POWER+GRENADE", deck = { "ESSENCE_TO_POWER", "GRENADE" } },
  { name = "mod:ZERO_DAMAGE+LIGHT_BULLET", deck = { "ZERO_DAMAGE", "LIGHT_BULLET" } },
  { name = "mod:ZERO_DAMAGE+BOUNCY_ORB", deck = { "ZERO_DAMAGE", "BOUNCY_ORB" } },
  { name = "mod:ZERO_DAMAGE+GRENADE", deck = { "ZERO_DAMAGE", "GRENADE" } },
  { name = "mod:HEAVY_SHOT+LIGHT_BULLET", deck = { "HEAVY_SHOT", "LIGHT_BULLET" } },
  { name = "mod:HEAVY_SHOT+BOUNCY_ORB", deck = { "HEAVY_SHOT", "BOUNCY_ORB" } },
  { name = "mod:HEAVY_SHOT+GRENADE", deck = { "HEAVY_SHOT", "GRENADE" } },
  { name = "mod:LIGHT_SHOT+LIGHT_BULLET", deck = { "LIGHT_SHOT", "LIGHT_BULLET" } },
  { name = "mod:LIGHT_SHOT+BOUNCY_ORB", deck = { "LIGHT_SHOT", "BOUNCY_ORB" } },
  { name = "mod:LIGHT_SHOT+GRENADE", deck = { "LIGHT_SHOT", "GRENADE" } },
  { name = "mod:KNOCKBACK+LIGHT_BULLET", deck = { "KNOCKBACK", "LIGHT_BULLET" } },
  { name = "mod:KNOCKBACK+BOUNCY_ORB", deck = { "KNOCKBACK", "BOUNCY_ORB" } },
  { name = "mod:KNOCKBACK+GRENADE", deck = { "KNOCKBACK", "GRENADE" } },
  { name = "mod:RECOIL+LIGHT_BULLET", deck = { "RECOIL", "LIGHT_BULLET" } },
  { name = "mod:RECOIL+BOUNCY_ORB", deck = { "RECOIL", "BOUNCY_ORB" } },
  { name = "mod:RECOIL+GRENADE", deck = { "RECOIL", "GRENADE" } },
  { name = "mod:RECOIL_DAMPER+LIGHT_BULLET", deck = { "RECOIL_DAMPER", "LIGHT_BULLET" } },
  { name = "mod:RECOIL_DAMPER+BOUNCY_ORB", deck = { "RECOIL_DAMPER", "BOUNCY_ORB" } },
  { name = "mod:RECOIL_DAMPER+GRENADE", deck = { "RECOIL_DAMPER", "GRENADE" } },
  { name = "mod:SPEED+LIGHT_BULLET", deck = { "SPEED", "LIGHT_BULLET" } },
  { name = "mod:SPEED+BOUNCY_ORB", deck = { "SPEED", "BOUNCY_ORB" } },
  { name = "mod:SPEED+GRENADE", deck = { "SPEED", "GRENADE" } },
  { name = "mod:ACCELERATING_SHOT+LIGHT_BULLET", deck = { "ACCELERATING_SHOT", "LIGHT_BULLET" } },
  { name = "mod:ACCELERATING_SHOT+BOUNCY_ORB", deck = { "ACCELERATING_SHOT", "BOUNCY_ORB" } },
  { name = "mod:ACCELERATING_SHOT+GRENADE", deck = { "ACCELERATING_SHOT", "GRENADE" } },
  { name = "mod:DECELERATING_SHOT+LIGHT_BULLET", deck = { "DECELERATING_SHOT", "LIGHT_BULLET" } },
  { name = "mod:DECELERATING_SHOT+BOUNCY_ORB", deck = { "DECELERATING_SHOT", "BOUNCY_ORB" } },
  { name = "mod:DECELERATING_SHOT+GRENADE", deck = { "DECELERATING_SHOT", "GRENADE" } },
  { name = "mod:EXPLOSIVE_PROJECTILE+LIGHT_BULLET", deck = { "EXPLOSIVE_PROJECTILE", "LIGHT_BULLET" } },
  { name = "mod:EXPLOSIVE_PROJECTILE+BOUNCY_ORB", deck = { "EXPLOSIVE_PROJECTILE", "BOUNCY_ORB" } },
  { name = "mod:EXPLOSIVE_PROJECTILE+GRENADE", deck = { "EXPLOSIVE_PROJECTILE", "GRENADE" } },
  { name = "mod:CLUSTERMOD+LIGHT_BULLET", deck = { "CLUSTERMOD", "LIGHT_BULLET" } },
  { name = "mod:CLUSTERMOD+BOUNCY_ORB", deck = { "CLUSTERMOD", "BOUNCY_ORB" } },
  { name = "mod:CLUSTERMOD+GRENADE", deck = { "CLUSTERMOD", "GRENADE" } },
  { name = "mod:WATER_TO_POISON+LIGHT_BULLET", deck = { "WATER_TO_POISON", "LIGHT_BULLET" } },
  { name = "mod:WATER_TO_POISON+BOUNCY_ORB", deck = { "WATER_TO_POISON", "BOUNCY_ORB" } },
  { name = "mod:WATER_TO_POISON+GRENADE", deck = { "WATER_TO_POISON", "GRENADE" } },
  { name = "mod:BLOOD_TO_ACID+LIGHT_BULLET", deck = { "BLOOD_TO_ACID", "LIGHT_BULLET" } },
  { name = "mod:BLOOD_TO_ACID+BOUNCY_ORB", deck = { "BLOOD_TO_ACID", "BOUNCY_ORB" } },
  { name = "mod:BLOOD_TO_ACID+GRENADE", deck = { "BLOOD_TO_ACID", "GRENADE" } },
  { name = "mod:LAVA_TO_BLOOD+LIGHT_BULLET", deck = { "LAVA_TO_BLOOD", "LIGHT_BULLET" } },
  { name = "mod:LAVA_TO_BLOOD+BOUNCY_ORB", deck = { "LAVA_TO_BLOOD", "BOUNCY_ORB" } },
  { name = "mod:LAVA_TO_BLOOD+GRENADE", deck = { "LAVA_TO_BLOOD", "GRENADE" } },
  { name = "mod:LIQUID_TO_EXPLOSION+LIGHT_BULLET", deck = { "LIQUID_TO_EXPLOSION", "LIGHT_BULLET" } },
  { name = "mod:LIQUID_TO_EXPLOSION+BOUNCY_ORB", deck = { "LIQUID_TO_EXPLOSION", "BOUNCY_ORB" } },
  { name = "mod:LIQUID_TO_EXPLOSION+GRENADE", deck = { "LIQUID_TO_EXPLOSION", "GRENADE" } },
  { name = "mod:TOXIC_TO_ACID+LIGHT_BULLET", deck = { "TOXIC_TO_ACID", "LIGHT_BULLET" } },
  { name = "mod:TOXIC_TO_ACID+BOUNCY_ORB", deck = { "TOXIC_TO_ACID", "BOUNCY_ORB" } },
  { name = "mod:TOXIC_TO_ACID+GRENADE", deck = { "TOXIC_TO_ACID", "GRENADE" } },
  { name = "mod:STATIC_TO_SAND+LIGHT_BULLET", deck = { "STATIC_TO_SAND", "LIGHT_BULLET" } },
  { name = "mod:STATIC_TO_SAND+BOUNCY_ORB", deck = { "STATIC_TO_SAND", "BOUNCY_ORB" } },
  { name = "mod:STATIC_TO_SAND+GRENADE", deck = { "STATIC_TO_SAND", "GRENADE" } },
  { name = "mod:TRANSMUTATION+LIGHT_BULLET", deck = { "TRANSMUTATION", "LIGHT_BULLET" } },
  { name = "mod:TRANSMUTATION+BOUNCY_ORB", deck = { "TRANSMUTATION", "BOUNCY_ORB" } },
  { name = "mod:TRANSMUTATION+GRENADE", deck = { "TRANSMUTATION", "GRENADE" } },
  { name = "mod:RANDOM_EXPLOSION+LIGHT_BULLET", deck = { "RANDOM_EXPLOSION", "LIGHT_BULLET" } },
  { name = "mod:RANDOM_EXPLOSION+BOUNCY_ORB", deck = { "RANDOM_EXPLOSION", "BOUNCY_ORB" } },
  { name = "mod:RANDOM_EXPLOSION+GRENADE", deck = { "RANDOM_EXPLOSION", "GRENADE" } },
  { name = "mod:NECROMANCY+LIGHT_BULLET", deck = { "NECROMANCY", "LIGHT_BULLET" } },
  { name = "mod:NECROMANCY+BOUNCY_ORB", deck = { "NECROMANCY", "BOUNCY_ORB" } },
  { name = "mod:NECROMANCY+GRENADE", deck = { "NECROMANCY", "GRENADE" } },
  { name = "mod:LIGHT+LIGHT_BULLET", deck = { "LIGHT", "LIGHT_BULLET" } },
  { name = "mod:LIGHT+BOUNCY_ORB", deck = { "LIGHT", "BOUNCY_ORB" } },
  { name = "mod:LIGHT+GRENADE", deck = { "LIGHT", "GRENADE" } },
  { name = "mod:ELECTRIC_CHARGE+LIGHT_BULLET", deck = { "ELECTRIC_CHARGE", "LIGHT_BULLET" } },
  { name = "mod:ELECTRIC_CHARGE+BOUNCY_ORB", deck = { "ELECTRIC_CHARGE", "BOUNCY_ORB" } },
  { name = "mod:ELECTRIC_CHARGE+GRENADE", deck = { "ELECTRIC_CHARGE", "GRENADE" } },
  { name = "mod:MATTER_EATER+LIGHT_BULLET", deck = { "MATTER_EATER", "LIGHT_BULLET" } },
  { name = "mod:MATTER_EATER+BOUNCY_ORB", deck = { "MATTER_EATER", "BOUNCY_ORB" } },
  { name = "mod:MATTER_EATER+GRENADE", deck = { "MATTER_EATER", "GRENADE" } },
  { name = "mod:FREEZE+LIGHT_BULLET", deck = { "FREEZE", "LIGHT_BULLET" } },
  { name = "mod:FREEZE+BOUNCY_ORB", deck = { "FREEZE", "BOUNCY_ORB" } },
  { name = "mod:FREEZE+GRENADE", deck = { "FREEZE", "GRENADE" } },
  { name = "mod:HITFX_BURNING_CRITICAL_HIT+LIGHT_BULLET", deck = { "HITFX_BURNING_CRITICAL_HIT", "LIGHT_BULLET" } },
  { name = "mod:HITFX_BURNING_CRITICAL_HIT+BOUNCY_ORB", deck = { "HITFX_BURNING_CRITICAL_HIT", "BOUNCY_ORB" } },
  { name = "mod:HITFX_BURNING_CRITICAL_HIT+GRENADE", deck = { "HITFX_BURNING_CRITICAL_HIT", "GRENADE" } },
  { name = "mod:HITFX_CRITICAL_WATER+LIGHT_BULLET", deck = { "HITFX_CRITICAL_WATER", "LIGHT_BULLET" } },
  { name = "mod:HITFX_CRITICAL_WATER+BOUNCY_ORB", deck = { "HITFX_CRITICAL_WATER", "BOUNCY_ORB" } },
  { name = "mod:HITFX_CRITICAL_WATER+GRENADE", deck = { "HITFX_CRITICAL_WATER", "GRENADE" } },
  { name = "mod:HITFX_CRITICAL_OIL+LIGHT_BULLET", deck = { "HITFX_CRITICAL_OIL", "LIGHT_BULLET" } },
  { name = "mod:HITFX_CRITICAL_OIL+BOUNCY_ORB", deck = { "HITFX_CRITICAL_OIL", "BOUNCY_ORB" } },
  { name = "mod:HITFX_CRITICAL_OIL+GRENADE", deck = { "HITFX_CRITICAL_OIL", "GRENADE" } },
  { name = "mod:HITFX_CRITICAL_BLOOD+LIGHT_BULLET", deck = { "HITFX_CRITICAL_BLOOD", "LIGHT_BULLET" } },
  { name = "mod:HITFX_CRITICAL_BLOOD+BOUNCY_ORB", deck = { "HITFX_CRITICAL_BLOOD", "BOUNCY_ORB" } },
  { name = "mod:HITFX_CRITICAL_BLOOD+GRENADE", deck = { "HITFX_CRITICAL_BLOOD", "GRENADE" } },
  { name = "mod:HITFX_TOXIC_CHARM+LIGHT_BULLET", deck = { "HITFX_TOXIC_CHARM", "LIGHT_BULLET" } },
  { name = "mod:HITFX_TOXIC_CHARM+BOUNCY_ORB", deck = { "HITFX_TOXIC_CHARM", "BOUNCY_ORB" } },
  { name = "mod:HITFX_TOXIC_CHARM+GRENADE", deck = { "HITFX_TOXIC_CHARM", "GRENADE" } },
  { name = "mod:HITFX_EXPLOSION_SLIME+LIGHT_BULLET", deck = { "HITFX_EXPLOSION_SLIME", "LIGHT_BULLET" } },
  { name = "mod:HITFX_EXPLOSION_SLIME+BOUNCY_ORB", deck = { "HITFX_EXPLOSION_SLIME", "BOUNCY_ORB" } },
  { name = "mod:HITFX_EXPLOSION_SLIME+GRENADE", deck = { "HITFX_EXPLOSION_SLIME", "GRENADE" } },
  { name = "mod:HITFX_EXPLOSION_SLIME_GIGA+LIGHT_BULLET", deck = { "HITFX_EXPLOSION_SLIME_GIGA", "LIGHT_BULLET" } },
  { name = "mod:HITFX_EXPLOSION_SLIME_GIGA+BOUNCY_ORB", deck = { "HITFX_EXPLOSION_SLIME_GIGA", "BOUNCY_ORB" } },
  { name = "mod:HITFX_EXPLOSION_SLIME_GIGA+GRENADE", deck = { "HITFX_EXPLOSION_SLIME_GIGA", "GRENADE" } },
  { name = "mod:HITFX_EXPLOSION_ALCOHOL+LIGHT_BULLET", deck = { "HITFX_EXPLOSION_ALCOHOL", "LIGHT_BULLET" } },
  { name = "mod:HITFX_EXPLOSION_ALCOHOL+BOUNCY_ORB", deck = { "HITFX_EXPLOSION_ALCOHOL", "BOUNCY_ORB" } },
  { name = "mod:HITFX_EXPLOSION_ALCOHOL+GRENADE", deck = { "HITFX_EXPLOSION_ALCOHOL", "GRENADE" } },
  { name = "mod:HITFX_EXPLOSION_ALCOHOL_GIGA+LIGHT_BULLET", deck = { "HITFX_EXPLOSION_ALCOHOL_GIGA", "LIGHT_BULLET" } },
  { name = "mod:HITFX_EXPLOSION_ALCOHOL_GIGA+BOUNCY_ORB", deck = { "HITFX_EXPLOSION_ALCOHOL_GIGA", "BOUNCY_ORB" } },
  { name = "mod:HITFX_EXPLOSION_ALCOHOL_GIGA+GRENADE", deck = { "HITFX_EXPLOSION_ALCOHOL_GIGA", "GRENADE" } },
  { name = "mod:HITFX_PETRIFY+LIGHT_BULLET", deck = { "HITFX_PETRIFY", "LIGHT_BULLET" } },
  { name = "mod:HITFX_PETRIFY+BOUNCY_ORB", deck = { "HITFX_PETRIFY", "BOUNCY_ORB" } },
  { name = "mod:HITFX_PETRIFY+GRENADE", deck = { "HITFX_PETRIFY", "GRENADE" } },
  { name = "mod:ROCKET_DOWNWARDS+LIGHT_BULLET", deck = { "ROCKET_DOWNWARDS", "LIGHT_BULLET" } },
  { name = "mod:ROCKET_DOWNWARDS+BOUNCY_ORB", deck = { "ROCKET_DOWNWARDS", "BOUNCY_ORB" } },
  { name = "mod:ROCKET_DOWNWARDS+GRENADE", deck = { "ROCKET_DOWNWARDS", "GRENADE" } },
  { name = "mod:ROCKET_OCTAGON+LIGHT_BULLET", deck = { "ROCKET_OCTAGON", "LIGHT_BULLET" } },
  { name = "mod:ROCKET_OCTAGON+BOUNCY_ORB", deck = { "ROCKET_OCTAGON", "BOUNCY_ORB" } },
  { name = "mod:ROCKET_OCTAGON+GRENADE", deck = { "ROCKET_OCTAGON", "GRENADE" } },
  { name = "mod:FIZZLE+LIGHT_BULLET", deck = { "FIZZLE", "LIGHT_BULLET" } },
  { name = "mod:FIZZLE+BOUNCY_ORB", deck = { "FIZZLE", "BOUNCY_ORB" } },
  { name = "mod:FIZZLE+GRENADE", deck = { "FIZZLE", "GRENADE" } },
  { name = "mod:BOUNCE_EXPLOSION+LIGHT_BULLET", deck = { "BOUNCE_EXPLOSION", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE_EXPLOSION+BOUNCY_ORB", deck = { "BOUNCE_EXPLOSION", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE_EXPLOSION+GRENADE", deck = { "BOUNCE_EXPLOSION", "GRENADE" } },
  { name = "mod:BOUNCE_SPARK+LIGHT_BULLET", deck = { "BOUNCE_SPARK", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE_SPARK+BOUNCY_ORB", deck = { "BOUNCE_SPARK", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE_SPARK+GRENADE", deck = { "BOUNCE_SPARK", "GRENADE" } },
  { name = "mod:BOUNCE_LASER+LIGHT_BULLET", deck = { "BOUNCE_LASER", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE_LASER+BOUNCY_ORB", deck = { "BOUNCE_LASER", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE_LASER+GRENADE", deck = { "BOUNCE_LASER", "GRENADE" } },
  { name = "mod:BOUNCE_LASER_EMITTER+LIGHT_BULLET", deck = { "BOUNCE_LASER_EMITTER", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE_LASER_EMITTER+BOUNCY_ORB", deck = { "BOUNCE_LASER_EMITTER", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE_LASER_EMITTER+GRENADE", deck = { "BOUNCE_LASER_EMITTER", "GRENADE" } },
  { name = "mod:BOUNCE_LARPA+LIGHT_BULLET", deck = { "BOUNCE_LARPA", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE_LARPA+BOUNCY_ORB", deck = { "BOUNCE_LARPA", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE_LARPA+GRENADE", deck = { "BOUNCE_LARPA", "GRENADE" } },
  { name = "mod:BOUNCE_SMALL_EXPLOSION+LIGHT_BULLET", deck = { "BOUNCE_SMALL_EXPLOSION", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE_SMALL_EXPLOSION+BOUNCY_ORB", deck = { "BOUNCE_SMALL_EXPLOSION", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE_SMALL_EXPLOSION+GRENADE", deck = { "BOUNCE_SMALL_EXPLOSION", "GRENADE" } },
  { name = "mod:BOUNCE_LIGHTNING+LIGHT_BULLET", deck = { "BOUNCE_LIGHTNING", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE_LIGHTNING+BOUNCY_ORB", deck = { "BOUNCE_LIGHTNING", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE_LIGHTNING+GRENADE", deck = { "BOUNCE_LIGHTNING", "GRENADE" } },
  { name = "mod:BOUNCE_HOLE+LIGHT_BULLET", deck = { "BOUNCE_HOLE", "LIGHT_BULLET" } },
  { name = "mod:BOUNCE_HOLE+BOUNCY_ORB", deck = { "BOUNCE_HOLE", "BOUNCY_ORB" } },
  { name = "mod:BOUNCE_HOLE+GRENADE", deck = { "BOUNCE_HOLE", "GRENADE" } },
  { name = "mod:FIREBALL_RAY+LIGHT_BULLET", deck = { "FIREBALL_RAY", "LIGHT_BULLET" } },
  { name = "mod:FIREBALL_RAY+BOUNCY_ORB", deck = { "FIREBALL_RAY", "BOUNCY_ORB" } },
  { name = "mod:FIREBALL_RAY+GRENADE", deck = { "FIREBALL_RAY", "GRENADE" } },
  { name = "mod:LIGHTNING_RAY+LIGHT_BULLET", deck = { "LIGHTNING_RAY", "LIGHT_BULLET" } },
  { name = "mod:LIGHTNING_RAY+BOUNCY_ORB", deck = { "LIGHTNING_RAY", "BOUNCY_ORB" } },
  { name = "mod:LIGHTNING_RAY+GRENADE", deck = { "LIGHTNING_RAY", "GRENADE" } },
  { name = "mod:TENTACLE_RAY+LIGHT_BULLET", deck = { "TENTACLE_RAY", "LIGHT_BULLET" } },
  { name = "mod:TENTACLE_RAY+BOUNCY_ORB", deck = { "TENTACLE_RAY", "BOUNCY_ORB" } },
  { name = "mod:TENTACLE_RAY+GRENADE", deck = { "TENTACLE_RAY", "GRENADE" } },
  { name = "mod:LASER_EMITTER_RAY+LIGHT_BULLET", deck = { "LASER_EMITTER_RAY", "LIGHT_BULLET" } },
  { name = "mod:LASER_EMITTER_RAY+BOUNCY_ORB", deck = { "LASER_EMITTER_RAY", "BOUNCY_ORB" } },
  { name = "mod:LASER_EMITTER_RAY+GRENADE", deck = { "LASER_EMITTER_RAY", "GRENADE" } },
  { name = "mod:FIREBALL_RAY_LINE+LIGHT_BULLET", deck = { "FIREBALL_RAY_LINE", "LIGHT_BULLET" } },
  { name = "mod:FIREBALL_RAY_LINE+BOUNCY_ORB", deck = { "FIREBALL_RAY_LINE", "BOUNCY_ORB" } },
  { name = "mod:FIREBALL_RAY_LINE+GRENADE", deck = { "FIREBALL_RAY_LINE", "GRENADE" } },
  { name = "mod:FIREBALL_RAY_ENEMY+LIGHT_BULLET", deck = { "FIREBALL_RAY_ENEMY", "LIGHT_BULLET" } },
  { name = "mod:FIREBALL_RAY_ENEMY+BOUNCY_ORB", deck = { "FIREBALL_RAY_ENEMY", "BOUNCY_ORB" } },
  { name = "mod:FIREBALL_RAY_ENEMY+GRENADE", deck = { "FIREBALL_RAY_ENEMY", "GRENADE" } },
  { name = "mod:LIGHTNING_RAY_ENEMY+LIGHT_BULLET", deck = { "LIGHTNING_RAY_ENEMY", "LIGHT_BULLET" } },
  { name = "mod:LIGHTNING_RAY_ENEMY+BOUNCY_ORB", deck = { "LIGHTNING_RAY_ENEMY", "BOUNCY_ORB" } },
  { name = "mod:LIGHTNING_RAY_ENEMY+GRENADE", deck = { "LIGHTNING_RAY_ENEMY", "GRENADE" } },
  { name = "mod:TENTACLE_RAY_ENEMY+LIGHT_BULLET", deck = { "TENTACLE_RAY_ENEMY", "LIGHT_BULLET" } },
  { name = "mod:TENTACLE_RAY_ENEMY+BOUNCY_ORB", deck = { "TENTACLE_RAY_ENEMY", "BOUNCY_ORB" } },
  { name = "mod:TENTACLE_RAY_ENEMY+GRENADE", deck = { "TENTACLE_RAY_ENEMY", "GRENADE" } },
  { name = "mod:GRAVITY_FIELD_ENEMY+LIGHT_BULLET", deck = { "GRAVITY_FIELD_ENEMY", "LIGHT_BULLET" } },
  { name = "mod:GRAVITY_FIELD_ENEMY+BOUNCY_ORB", deck = { "GRAVITY_FIELD_ENEMY", "BOUNCY_ORB" } },
  { name = "mod:GRAVITY_FIELD_ENEMY+GRENADE", deck = { "GRAVITY_FIELD_ENEMY", "GRENADE" } },
  { name = "mod:CURSE+LIGHT_BULLET", deck = { "CURSE", "LIGHT_BULLET" } },
  { name = "mod:CURSE+BOUNCY_ORB", deck = { "CURSE", "BOUNCY_ORB" } },
  { name = "mod:CURSE+GRENADE", deck = { "CURSE", "GRENADE" } },
  { name = "mod:CURSE_WITHER_PROJECTILE+LIGHT_BULLET", deck = { "CURSE_WITHER_PROJECTILE", "LIGHT_BULLET" } },
  { name = "mod:CURSE_WITHER_PROJECTILE+BOUNCY_ORB", deck = { "CURSE_WITHER_PROJECTILE", "BOUNCY_ORB" } },
  { name = "mod:CURSE_WITHER_PROJECTILE+GRENADE", deck = { "CURSE_WITHER_PROJECTILE", "GRENADE" } },
  { name = "mod:CURSE_WITHER_EXPLOSION+LIGHT_BULLET", deck = { "CURSE_WITHER_EXPLOSION", "LIGHT_BULLET" } },
  { name = "mod:CURSE_WITHER_EXPLOSION+BOUNCY_ORB", deck = { "CURSE_WITHER_EXPLOSION", "BOUNCY_ORB" } },
  { name = "mod:CURSE_WITHER_EXPLOSION+GRENADE", deck = { "CURSE_WITHER_EXPLOSION", "GRENADE" } },
  { name = "mod:CURSE_WITHER_MELEE+LIGHT_BULLET", deck = { "CURSE_WITHER_MELEE", "LIGHT_BULLET" } },
  { name = "mod:CURSE_WITHER_MELEE+BOUNCY_ORB", deck = { "CURSE_WITHER_MELEE", "BOUNCY_ORB" } },
  { name = "mod:CURSE_WITHER_MELEE+GRENADE", deck = { "CURSE_WITHER_MELEE", "GRENADE" } },
  { name = "mod:CURSE_WITHER_ELECTRICITY+LIGHT_BULLET", deck = { "CURSE_WITHER_ELECTRICITY", "LIGHT_BULLET" } },
  { name = "mod:CURSE_WITHER_ELECTRICITY+BOUNCY_ORB", deck = { "CURSE_WITHER_ELECTRICITY", "BOUNCY_ORB" } },
  { name = "mod:CURSE_WITHER_ELECTRICITY+GRENADE", deck = { "CURSE_WITHER_ELECTRICITY", "GRENADE" } },
  { name = "mod:ORBIT_DISCS+LIGHT_BULLET", deck = { "ORBIT_DISCS", "LIGHT_BULLET" } },
  { name = "mod:ORBIT_DISCS+BOUNCY_ORB", deck = { "ORBIT_DISCS", "BOUNCY_ORB" } },
  { name = "mod:ORBIT_DISCS+GRENADE", deck = { "ORBIT_DISCS", "GRENADE" } },
  { name = "mod:ORBIT_FIREBALLS+LIGHT_BULLET", deck = { "ORBIT_FIREBALLS", "LIGHT_BULLET" } },
  { name = "mod:ORBIT_FIREBALLS+BOUNCY_ORB", deck = { "ORBIT_FIREBALLS", "BOUNCY_ORB" } },
  { name = "mod:ORBIT_FIREBALLS+GRENADE", deck = { "ORBIT_FIREBALLS", "GRENADE" } },
  { name = "mod:ORBIT_NUKES+LIGHT_BULLET", deck = { "ORBIT_NUKES", "LIGHT_BULLET" } },
  { name = "mod:ORBIT_NUKES+BOUNCY_ORB", deck = { "ORBIT_NUKES", "BOUNCY_ORB" } },
  { name = "mod:ORBIT_NUKES+GRENADE", deck = { "ORBIT_NUKES", "GRENADE" } },
  { name = "mod:ORBIT_LASERS+LIGHT_BULLET", deck = { "ORBIT_LASERS", "LIGHT_BULLET" } },
  { name = "mod:ORBIT_LASERS+BOUNCY_ORB", deck = { "ORBIT_LASERS", "BOUNCY_ORB" } },
  { name = "mod:ORBIT_LASERS+GRENADE", deck = { "ORBIT_LASERS", "GRENADE" } },
  { name = "mod:ORBIT_LARPA+LIGHT_BULLET", deck = { "ORBIT_LARPA", "LIGHT_BULLET" } },
  { name = "mod:ORBIT_LARPA+BOUNCY_ORB", deck = { "ORBIT_LARPA", "BOUNCY_ORB" } },
  { name = "mod:ORBIT_LARPA+GRENADE", deck = { "ORBIT_LARPA", "GRENADE" } },
  { name = "mod:CHAIN_SHOT+LIGHT_BULLET", deck = { "CHAIN_SHOT", "LIGHT_BULLET" } },
  { name = "mod:CHAIN_SHOT+BOUNCY_ORB", deck = { "CHAIN_SHOT", "BOUNCY_ORB" } },
  { name = "mod:CHAIN_SHOT+GRENADE", deck = { "CHAIN_SHOT", "GRENADE" } },
  { name = "mod:ARC_ELECTRIC+LIGHT_BULLET", deck = { "ARC_ELECTRIC", "LIGHT_BULLET" } },
  { name = "mod:ARC_ELECTRIC+BOUNCY_ORB", deck = { "ARC_ELECTRIC", "BOUNCY_ORB" } },
  { name = "mod:ARC_ELECTRIC+GRENADE", deck = { "ARC_ELECTRIC", "GRENADE" } },
  { name = "mod:ARC_FIRE+LIGHT_BULLET", deck = { "ARC_FIRE", "LIGHT_BULLET" } },
  { name = "mod:ARC_FIRE+BOUNCY_ORB", deck = { "ARC_FIRE", "BOUNCY_ORB" } },
  { name = "mod:ARC_FIRE+GRENADE", deck = { "ARC_FIRE", "GRENADE" } },
  { name = "mod:ARC_GUNPOWDER+LIGHT_BULLET", deck = { "ARC_GUNPOWDER", "LIGHT_BULLET" } },
  { name = "mod:ARC_GUNPOWDER+BOUNCY_ORB", deck = { "ARC_GUNPOWDER", "BOUNCY_ORB" } },
  { name = "mod:ARC_GUNPOWDER+GRENADE", deck = { "ARC_GUNPOWDER", "GRENADE" } },
  { name = "mod:ARC_POISON+LIGHT_BULLET", deck = { "ARC_POISON", "LIGHT_BULLET" } },
  { name = "mod:ARC_POISON+BOUNCY_ORB", deck = { "ARC_POISON", "BOUNCY_ORB" } },
  { name = "mod:ARC_POISON+GRENADE", deck = { "ARC_POISON", "GRENADE" } },
  { name = "mod:CRUMBLING_EARTH_PROJECTILE+LIGHT_BULLET", deck = { "CRUMBLING_EARTH_PROJECTILE", "LIGHT_BULLET" } },
  { name = "mod:CRUMBLING_EARTH_PROJECTILE+BOUNCY_ORB", deck = { "CRUMBLING_EARTH_PROJECTILE", "BOUNCY_ORB" } },
  { name = "mod:CRUMBLING_EARTH_PROJECTILE+GRENADE", deck = { "CRUMBLING_EARTH_PROJECTILE", "GRENADE" } },
  { name = "mod:UNSTABLE_GUNPOWDER+LIGHT_BULLET", deck = { "UNSTABLE_GUNPOWDER", "LIGHT_BULLET" } },
  { name = "mod:UNSTABLE_GUNPOWDER+BOUNCY_ORB", deck = { "UNSTABLE_GUNPOWDER", "BOUNCY_ORB" } },
  { name = "mod:UNSTABLE_GUNPOWDER+GRENADE", deck = { "UNSTABLE_GUNPOWDER", "GRENADE" } },
  { name = "mod:ACID_TRAIL+LIGHT_BULLET", deck = { "ACID_TRAIL", "LIGHT_BULLET" } },
  { name = "mod:ACID_TRAIL+BOUNCY_ORB", deck = { "ACID_TRAIL", "BOUNCY_ORB" } },
  { name = "mod:ACID_TRAIL+GRENADE", deck = { "ACID_TRAIL", "GRENADE" } },
  { name = "mod:POISON_TRAIL+LIGHT_BULLET", deck = { "POISON_TRAIL", "LIGHT_BULLET" } },
  { name = "mod:POISON_TRAIL+BOUNCY_ORB", deck = { "POISON_TRAIL", "BOUNCY_ORB" } },
  { name = "mod:POISON_TRAIL+GRENADE", deck = { "POISON_TRAIL", "GRENADE" } },
  { name = "mod:OIL_TRAIL+LIGHT_BULLET", deck = { "OIL_TRAIL", "LIGHT_BULLET" } },
  { name = "mod:OIL_TRAIL+BOUNCY_ORB", deck = { "OIL_TRAIL", "BOUNCY_ORB" } },
  { name = "mod:OIL_TRAIL+GRENADE", deck = { "OIL_TRAIL", "GRENADE" } },
  { name = "mod:WATER_TRAIL+LIGHT_BULLET", deck = { "WATER_TRAIL", "LIGHT_BULLET" } },
  { name = "mod:WATER_TRAIL+BOUNCY_ORB", deck = { "WATER_TRAIL", "BOUNCY_ORB" } },
  { name = "mod:WATER_TRAIL+GRENADE", deck = { "WATER_TRAIL", "GRENADE" } },
  { name = "mod:GUNPOWDER_TRAIL+LIGHT_BULLET", deck = { "GUNPOWDER_TRAIL", "LIGHT_BULLET" } },
  { name = "mod:GUNPOWDER_TRAIL+BOUNCY_ORB", deck = { "GUNPOWDER_TRAIL", "BOUNCY_ORB" } },
  { name = "mod:GUNPOWDER_TRAIL+GRENADE", deck = { "GUNPOWDER_TRAIL", "GRENADE" } },
  { name = "mod:FIRE_TRAIL+LIGHT_BULLET", deck = { "FIRE_TRAIL", "LIGHT_BULLET" } },
  { name = "mod:FIRE_TRAIL+BOUNCY_ORB", deck = { "FIRE_TRAIL", "BOUNCY_ORB" } },
  { name = "mod:FIRE_TRAIL+GRENADE", deck = { "FIRE_TRAIL", "GRENADE" } },
  { name = "mod:BURN_TRAIL+LIGHT_BULLET", deck = { "BURN_TRAIL", "LIGHT_BULLET" } },
  { name = "mod:BURN_TRAIL+BOUNCY_ORB", deck = { "BURN_TRAIL", "BOUNCY_ORB" } },
  { name = "mod:BURN_TRAIL+GRENADE", deck = { "BURN_TRAIL", "GRENADE" } },
  { name = "mod:ENERGY_SHIELD_SHOT+LIGHT_BULLET", deck = { "ENERGY_SHIELD_SHOT", "LIGHT_BULLET" } },
  { name = "mod:ENERGY_SHIELD_SHOT+BOUNCY_ORB", deck = { "ENERGY_SHIELD_SHOT", "BOUNCY_ORB" } },
  { name = "mod:ENERGY_SHIELD_SHOT+GRENADE", deck = { "ENERGY_SHIELD_SHOT", "GRENADE" } },
  { name = "mod:RANDOM_MODIFIER+LIGHT_BULLET", deck = { "RANDOM_MODIFIER", "LIGHT_BULLET" } },
  { name = "mod:RANDOM_MODIFIER+BOUNCY_ORB", deck = { "RANDOM_MODIFIER", "BOUNCY_ORB" } },
  { name = "mod:RANDOM_MODIFIER+GRENADE", deck = { "RANDOM_MODIFIER", "GRENADE" } },
  { name = "mod:LARPA_CHAOS+LIGHT_BULLET", deck = { "LARPA_CHAOS", "LIGHT_BULLET" } },
  { name = "mod:LARPA_CHAOS+BOUNCY_ORB", deck = { "LARPA_CHAOS", "BOUNCY_ORB" } },
  { name = "mod:LARPA_CHAOS+GRENADE", deck = { "LARPA_CHAOS", "GRENADE" } },
  { name = "mod:LARPA_DOWNWARDS+LIGHT_BULLET", deck = { "LARPA_DOWNWARDS", "LIGHT_BULLET" } },
  { name = "mod:LARPA_DOWNWARDS+BOUNCY_ORB", deck = { "LARPA_DOWNWARDS", "BOUNCY_ORB" } },
  { name = "mod:LARPA_DOWNWARDS+GRENADE", deck = { "LARPA_DOWNWARDS", "GRENADE" } },
  { name = "mod:LARPA_UPWARDS+LIGHT_BULLET", deck = { "LARPA_UPWARDS", "LIGHT_BULLET" } },
  { name = "mod:LARPA_UPWARDS+BOUNCY_ORB", deck = { "LARPA_UPWARDS", "BOUNCY_ORB" } },
  { name = "mod:LARPA_UPWARDS+GRENADE", deck = { "LARPA_UPWARDS", "GRENADE" } },
  { name = "mod:LARPA_CHAOS_2+LIGHT_BULLET", deck = { "LARPA_CHAOS_2", "LIGHT_BULLET" } },
  { name = "mod:LARPA_CHAOS_2+BOUNCY_ORB", deck = { "LARPA_CHAOS_2", "BOUNCY_ORB" } },
  { name = "mod:LARPA_CHAOS_2+GRENADE", deck = { "LARPA_CHAOS_2", "GRENADE" } },
  { name = "mod:LARPA_DEATH+LIGHT_BULLET", deck = { "LARPA_DEATH", "LIGHT_BULLET" } },
  { name = "mod:LARPA_DEATH+BOUNCY_ORB", deck = { "LARPA_DEATH", "BOUNCY_ORB" } },
  { name = "mod:LARPA_DEATH+GRENADE", deck = { "LARPA_DEATH", "GRENADE" } },
  { name = "mod:COLOUR_RED+LIGHT_BULLET", deck = { "COLOUR_RED", "LIGHT_BULLET" } },
  { name = "mod:COLOUR_RED+BOUNCY_ORB", deck = { "COLOUR_RED", "BOUNCY_ORB" } },
  { name = "mod:COLOUR_RED+GRENADE", deck = { "COLOUR_RED", "GRENADE" } },
  { name = "mod:COLOUR_ORANGE+LIGHT_BULLET", deck = { "COLOUR_ORANGE", "LIGHT_BULLET" } },
  { name = "mod:COLOUR_ORANGE+BOUNCY_ORB", deck = { "COLOUR_ORANGE", "BOUNCY_ORB" } },
  { name = "mod:COLOUR_ORANGE+GRENADE", deck = { "COLOUR_ORANGE", "GRENADE" } },
  { name = "mod:COLOUR_GREEN+LIGHT_BULLET", deck = { "COLOUR_GREEN", "LIGHT_BULLET" } },
  { name = "mod:COLOUR_GREEN+BOUNCY_ORB", deck = { "COLOUR_GREEN", "BOUNCY_ORB" } },
  { name = "mod:COLOUR_GREEN+GRENADE", deck = { "COLOUR_GREEN", "GRENADE" } },
  { name = "mod:COLOUR_YELLOW+LIGHT_BULLET", deck = { "COLOUR_YELLOW", "LIGHT_BULLET" } },
  { name = "mod:COLOUR_YELLOW+BOUNCY_ORB", deck = { "COLOUR_YELLOW", "BOUNCY_ORB" } },
  { name = "mod:COLOUR_YELLOW+GRENADE", deck = { "COLOUR_YELLOW", "GRENADE" } },
  { name = "mod:COLOUR_PURPLE+LIGHT_BULLET", deck = { "COLOUR_PURPLE", "LIGHT_BULLET" } },
  { name = "mod:COLOUR_PURPLE+BOUNCY_ORB", deck = { "COLOUR_PURPLE", "BOUNCY_ORB" } },
  { name = "mod:COLOUR_PURPLE+GRENADE", deck = { "COLOUR_PURPLE", "GRENADE" } },
  { name = "mod:COLOUR_BLUE+LIGHT_BULLET", deck = { "COLOUR_BLUE", "LIGHT_BULLET" } },
  { name = "mod:COLOUR_BLUE+BOUNCY_ORB", deck = { "COLOUR_BLUE", "BOUNCY_ORB" } },
  { name = "mod:COLOUR_BLUE+GRENADE", deck = { "COLOUR_BLUE", "GRENADE" } },
  { name = "mod:COLOUR_RAINBOW+LIGHT_BULLET", deck = { "COLOUR_RAINBOW", "LIGHT_BULLET" } },
  { name = "mod:COLOUR_RAINBOW+BOUNCY_ORB", deck = { "COLOUR_RAINBOW", "BOUNCY_ORB" } },
  { name = "mod:COLOUR_RAINBOW+GRENADE", deck = { "COLOUR_RAINBOW", "GRENADE" } },
  { name = "mod:COLOUR_INVIS+LIGHT_BULLET", deck = { "COLOUR_INVIS", "LIGHT_BULLET" } },
  { name = "mod:COLOUR_INVIS+BOUNCY_ORB", deck = { "COLOUR_INVIS", "BOUNCY_ORB" } },
  { name = "mod:COLOUR_INVIS+GRENADE", deck = { "COLOUR_INVIS", "GRENADE" } },
  { name = "mod:RAINBOW_TRAIL+LIGHT_BULLET", deck = { "RAINBOW_TRAIL", "LIGHT_BULLET" } },
  { name = "mod:RAINBOW_TRAIL+BOUNCY_ORB", deck = { "RAINBOW_TRAIL", "BOUNCY_ORB" } },
  { name = "mod:RAINBOW_TRAIL+GRENADE", deck = { "RAINBOW_TRAIL", "GRENADE" } },
  { name = "combo:BURST_2+LIGHT_BULLET+BOUNCY_ORB", deck = { "BURST_2", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:BURST_3+LIGHT_BULLET+BOUNCY_ORB+GRENADE", deck = { "BURST_3", "LIGHT_BULLET", "BOUNCY_ORB", "GRENADE" } },
  { name = "combo:BURST_4+LIGHT_BULLET+LIGHT_BULLET+BOUNCY_ORB+GRENADE", deck = { "BURST_4", "LIGHT_BULLET", "LIGHT_BULLET", "BOUNCY_ORB", "GRENADE" } },
  { name = "combo:SCATTER_2+LIGHT_BULLET+LIGHT_BULLET", deck = { "SCATTER_2", "LIGHT_BULLET", "LIGHT_BULLET" } },
  { name = "combo:SCATTER_3+LIGHT_BULLET+LIGHT_BULLET+LIGHT_BULLET", deck = { "SCATTER_3", "LIGHT_BULLET", "LIGHT_BULLET", "LIGHT_BULLET" } },
  { name = "combo:SCATTER_4+LIGHT_BULLET+LIGHT_BULLET+LIGHT_BULLET+LIGHT_BULLET", deck = { "SCATTER_4", "LIGHT_BULLET", "LIGHT_BULLET", "LIGHT_BULLET", "LIGHT_BULLET" } },
  { name = "combo:ADD_TRIGGER+LIGHT_BULLET+BOUNCY_ORB", deck = { "ADD_TRIGGER", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:ADD_TIMER+LIGHT_BULLET+BOUNCY_ORB", deck = { "ADD_TIMER", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:ADD_DEATH_TRIGGER+LIGHT_BULLET+BOUNCY_ORB", deck = { "ADD_DEATH_TRIGGER", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:ADD_TRIGGER+LIGHT_BULLET+BURST_2+BOUNCY_ORB+GRENADE", deck = { "ADD_TRIGGER", "LIGHT_BULLET", "BURST_2", "BOUNCY_ORB", "GRENADE" } },
  { name = "combo:DIVIDE_2+LIGHT_BULLET", deck = { "DIVIDE_2", "LIGHT_BULLET" } },
  { name = "combo:DIVIDE_3+LIGHT_BULLET", deck = { "DIVIDE_3", "LIGHT_BULLET" } },
  { name = "combo:DIVIDE_4+LIGHT_BULLET", deck = { "DIVIDE_4", "LIGHT_BULLET" } },
  { name = "combo:DIVIDE_10+LIGHT_BULLET", deck = { "DIVIDE_10", "LIGHT_BULLET" } },
  { name = "combo:HOMING+BURST_2+LIGHT_BULLET+BOUNCY_ORB", deck = { "HOMING", "BURST_2", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:DAMAGE+HEAVY_SHOT+LIGHT_BULLET", deck = { "DAMAGE", "HEAVY_SHOT", "LIGHT_BULLET" } },
  { name = "combo:ALPHA+LIGHT_BULLET+BOUNCY_ORB", deck = { "ALPHA", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:GAMMA+LIGHT_BULLET+BOUNCY_ORB", deck = { "GAMMA", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:TAU+LIGHT_BULLET+BOUNCY_ORB+GRENADE", deck = { "TAU", "LIGHT_BULLET", "BOUNCY_ORB", "GRENADE" } },
  { name = "combo:OMEGA+LIGHT_BULLET+BOUNCY_ORB", deck = { "OMEGA", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:MU+HOMING+DAMAGE+LIGHT_BULLET", deck = { "MU", "HOMING", "DAMAGE", "LIGHT_BULLET" } },
  { name = "combo:PHI+LIGHT_BULLET+BOUNCY_ORB", deck = { "PHI", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:SIGMA+LIGHT_BULLET+BOUNCY_ORB", deck = { "SIGMA", "LIGHT_BULLET", "BOUNCY_ORB" } },
  { name = "combo:ZETA+LIGHT_BULLET", deck = { "ZETA", "LIGHT_BULLET" } },
  { name = "wand:1-00", deck = { "SCATTER_3", "LIGHT", "SPITTER", "SPITTER" }, spells_per_cast = 1, spread = 2, speed_multiplier = 1.001, always_cast = { } },
  { name = "wand:2-01", deck = { "SCATTER_3", "ARC_GUNPOWDER", "MIST_RADIOACTIVE", "MIST_RADIOACTIVE", "MIST_RADIOACTIVE", "MIST_RADIOACTIVE" }, spells_per_cast = 2, spread = 8, speed_multiplier = 1.167, always_cast = { } },
  { name = "wand:3-02", deck = { "SCATTER_2", "UNSTABLE_GUNPOWDER", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET", "DISC_BULLET" }, spells_per_cast = 1, spread = 35, speed_multiplier = 0.94, always_cast = { } },
  { name = "wand:4-03", deck = { "BURST_4", "LASER_EMITTER_RAY", "PIPE_BOMB", "PIPE_BOMB", "PIPE_BOMB", "PIPE_BOMB", "PIPE_BOMB", "PIPE_BOMB", "PIPE_BOMB" }, spells_per_cast = 1, spread = -1, speed_multiplier = 1.081, always_cast = { } },
  { name = "wand:5-04", deck = { "BURST_4", "SPITTER_TIER_2", "ARC_GUNPOWDER", "FIREBALL", "SLOW_BULLET", "FIREBALL_RAY" }, spells_per_cast = 1, spread = -1, speed_multiplier = 0.909, always_cast = { } },
  { name = "wand:6-05", deck = { "PROPANE_TANK", "PROPANE_TANK", "PROPANE_TANK", "PROPANE_TANK", "PROPANE_TANK", "PROPANE_TANK", "PROPANE_TANK", "PROPANE_TANK", "PROPANE_TANK", "PROPANE_TANK" }, spells_per_cast = 3, spread = -5, speed_multiplier = 0.803, always_cast = { } },
  { name = "wand:1-06", deck = { "LASER_EMITTER_CUTTER", "LASER_EMITTER_CUTTER" }, spells_per_cast = 2, spread = -5, speed_multiplier = 0.939, always_cast = { } },
  { name = "wand:2-07", deck = { "BURST_2", "SPEED", "GLITTER_BOMB", "GLITTER_BOMB", "GLITTER_BOMB" }, spells_per_cast = 1, spread = 2, speed_multiplier = 1.154, always_cast = { } },
  { name = "wand:3-08", deck = { "MIST_ALCOHOL", "MIST_ALCOHOL", "SCATTER_2" }, spells_per_cast = 2, spread = -19, speed_multiplier = 0.976, always_cast = { } },
  { name = "wand:4-09", deck = { "BURST_3", "BURST_2", "COLOUR_INVIS", "MINE", "MINE", "MINE", "MINE", "MINE", "MINE", "MINE", "MINE", "MINE", "MINE", "MINE" }, spells_per_cast = 1, spread = 2, speed_multiplier = 1.016, always_cast = { } },
  { name = "wand:5-10", deck = { "AUTOAIM", "BUCKSHOT", "BUCKSHOT", "BUCKSHOT" }, spells_per_cast = 1, spread = 2, speed_multiplier = 0.924, always_cast = { } },
  { name = "wand:6-11", deck = { "TELEPORT_PROJECTILE", "GRENADE_TRIGGER", "BOMB_CART", "SCATTER_4", "DARKFLAME", "LIFETIME", "PROPANE_TANK", "TELEPORT_PROJECTILE_STATIC", "PIPE_BOMB_DEATH_TRIGGER", "SPITTER_TIER_3" }, spells_per_cast = 1, spread = -31, speed_multiplier = 1.036, always_cast = { } },
  { name = "wand:1-12", deck = { "LIGHT_BULLET", "LIGHT_BULLET" }, spells_per_cast = 3, spread = -0, speed_multiplier = 1.194, always_cast = { } },
  { name = "wand:2-13", deck = { "SLOW_BULLET", "ORBIT_DISCS", "SLOW_BULLET", "SLOW_BULLET" }, spells_per_cast = 2, spread = -3, speed_multiplier = 1.163, always_cast = { } },
  { name = "wand:3-14", deck = { "I_SHAPE", "ESSENCE_TO_POWER", "MIST_ALCOHOL", "MIST_ALCOHOL", "MIST_ALCOHOL", "MIST_ALCOHOL", "MIST_ALCOHOL" }, spells_per_cast = 1, spread = 1, speed_multiplier = 1.022, always_cast = { } },
  { name = "wand:4-15", deck = { "TENTACLE", "TENTACLE" }, spells_per_cast = 4, spread = -2, speed_multiplier = 0.827, always_cast = { } },
  { name = "wand:5-16", deck = { "LASER_EMITTER", "LASER_EMITTER", "LASER_EMITTER", "BURST_3" }, spells_per_cast = 1, spread = -3, speed_multiplier = 1.062, always_cast = { } },
  { name = "wand:6-17", deck = { "EXPLOSION_REMOVE", "TENTACLE", "TENTACLE", "TENTACLE", "TENTACLE" }, spells_per_cast = 1, spread = 0, speed_multiplier = 1.159, always_cast = { } },
  { name = "wand:1-18", deck = { "BUBBLESHOT", "BUBBLESHOT", "BURST_2", "BUBBLESHOT" }, spells_per_cast = 1, spread = -2, speed_multiplier = 1.142, always_cast = { } },
  { name = "wand:2-19", deck = { "SPITTER" }, spells_per_cast = 3, spread = 4, speed_multiplier = 1.158, always_cast = { } },
  { name = "wand:3-20", deck = { "LUMINOUS_DRILL", "LUMINOUS_DRILL", "BURST_2" }, spells_per_cast = 1, spread = -5, speed_multiplier = 1.194, always_cast = { } },
  { name = "wand:4-21", deck = { "I_SHAPE", "T_SHAPE", "FREEZE", "HOOK", "HOOK", "HOOK", "HOOK", "HOOK" }, spells_per_cast = 1, spread = -5, speed_multiplier = 0.896, always_cast = { } },
  { name = "wand:5-22", deck = { "SPITTER_TIER_3", "SPITTER_TIER_3", "SPITTER_TIER_3", "SPITTER_TIER_3", "SPITTER_TIER_3", "SPITTER_TIER_3", "SPITTER_TIER_3" }, spells_per_cast = 1, spread = -7, speed_multiplier = 1.012, always_cast = { } },
  { name = "wand:6-23", deck = { "PROPANE_TANK", "LASER_EMITTER_FOUR", "PROPANE_TANK", "TNTBOX_BIG", "DISC_BULLET_BIGGER", "ARROW", "BULLET_TIMER", "CRUMBLING_EARTH", "CHAIN_BOLT", "LIGHTNING_RAY_ENEMY", "SPITTER_TIER_3", "BLACK_HOLE", "SLOW_BULLET_TRIGGER", "SPORE_POD", "BULLET", "WORM_SHOT", "LANCE_HOLY", "BOMB_CART", "DISC_BULLET_BIGGER", "BULLET" }, spells_per_cast = 12, spread = -4, speed_multiplier = 0.971, always_cast = { } },
  { name = "wand:1-24", deck = { "BURST_2", "FIRE_TRAIL", "BOMB", "BOMB" }, spells_per_cast = 1, spread = 1, speed_multiplier = 0.848, always_cast = { } },
  { name = "wand:2-25", deck = { "BULLET_TRIGGER", "BULLET_TRIGGER", "BURST_2" }, spells_per_cast = 1, spread = 1, speed_multiplier = 1.155, always_cast = { } },
  { name = "wand:3-26", deck = { "TELEPORT_PROJECTILE_CLOSER", "PENTAGRAM_SHAPE", "SPITTER_TIER_2", "AUTOAIM", "PROPANE_TANK", "ICEBALL", "DEATH_CROSS_BIG", "HEAVY_BULLET", "LASER_EMITTER_FOUR" }, spells_per_cast = 1, spread = 2, speed_multiplier = 0.994, always_cast = { } },
  { name = "wand:4-27", deck = { "SCATTER_4", "MINE", "MINE", "MINE", "MINE", "MINE", "MINE" }, spells_per_cast = 1, spread = -2, speed_multiplier = 1, always_cast = { } },
  { name = "wand:5-28", deck = { "BURST_4", "BURST_3", "ACCELERATING_SHOT", "CHAIN_BOLT", "CHAIN_BOLT", "CHAIN_BOLT" }, spells_per_cast = 2, spread = 6, speed_multiplier = 1.057, always_cast = { } },
  { name = "wand:6-29", deck = { "BURST_3", "EXPLOSION_TINY", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_2_TIMER" }, spells_per_cast = 1, spread = -5, speed_multiplier = 0.959, always_cast = { } },
  { name = "wand:1-30", deck = { "SCATTER_2", "FIRE_TRAIL", "GRENADE_TRIGGER", "GRENADE_TRIGGER" }, spells_per_cast = 1, spread = 5, speed_multiplier = 0.97, always_cast = { } },
  { name = "wand:2-31", deck = { "TELEPORT_PROJECTILE_CLOSER", "TELEPORT_PROJECTILE_CLOSER" }, spells_per_cast = 1, spread = -1, speed_multiplier = 1.046, always_cast = { } },
  { name = "wand:3-32", deck = { "ACIDSHOT" }, spells_per_cast = 1, spread = 3, speed_multiplier = 0.98, always_cast = { } },
  { name = "wand:4-33", deck = { "BULLET", "BULLET", "BULLET" }, spells_per_cast = 1, spread = 1, speed_multiplier = 1.005, always_cast = { } },
  { name = "wand:5-34", deck = { "HEAVY_BULLET_TIMER", "SCATTER_4", "SPORE_POD", "DAMAGE_FOREVER", "BOMB", "METEOR", "SCATTER_4", "SPIRAL_SHOT" }, spells_per_cast = 1, spread = -2, speed_multiplier = 0.978, always_cast = { } },
  { name = "wand:6-35", deck = { "SLOW_BULLET_TRIGGER", "LIGHTNING_RAY_ENEMY", "SLOW_BULLET_TRIGGER", "SLOW_BULLET_TRIGGER", "SLOW_BULLET_TRIGGER", "SLOW_BULLET_TRIGGER", "SLOW_BULLET_TRIGGER", "FIREBALL_RAY", "SLOW_BULLET_TRIGGER", "SLOW_BULLET_TRIGGER" }, spells_per_cast = 2, spread = 2, speed_multiplier = 0.943, always_cast = { } },
  { name = "wand:1-36", deck = { "LUMINOUS_DRILL", "SCATTER_2", "LUMINOUS_DRILL" }, spells_per_cast = 1, spread = 2, speed_multiplier = 0.976, always_cast = { } },
  { name = "wand:2-37", deck = { "FIREBALL_RAY", "MIST_ALCOHOL", "MIST_ALCOHOL", "MIST_ALCOHOL" }, spells_per_cast = 1, spread = -12, speed_multiplier = 0.812, always_cast = { } },
  { name = "wand:3-38", deck = { "SCATTER_3", "LIGHTNING_RAY", "TNTBOX", "TNTBOX" }, spells_per_cast = 1, spread = -2, speed_multiplier = 0.847, always_cast = { } },
  { name = "wand:4-39", deck = { "SLIMEBALL", "SLIMEBALL", "SLIMEBALL", "SLIMEBALL", "SCATTER_3" }, spells_per_cast = 1, spread = 3, speed_multiplier = 1.08, always_cast = { } },
  { name = "wand:5-40", deck = { "BURST_3", "GLOWING_BOLT", "BURST_4", "GLOWING_BOLT", "GLOWING_BOLT", "GLOWING_BOLT" }, spells_per_cast = 1, spread = -0, speed_multiplier = 0.999, always_cast = { "ARC_GUNPOWDER" } },
  { name = "wand:6-41", deck = { "PIERCING_SHOT", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE", "LANCE" }, spells_per_cast = 1, spread = 3, speed_multiplier = 0.912, always_cast = { } },
  { name = "wand:1-42", deck = { "SUMMON_ROCK", "Y_SHAPE", "SUMMON_ROCK" }, spells_per_cast = 1, spread = 3, speed_multiplier = 0.952, always_cast = { } },
  { name = "wand:2-43", deck = { "BURST_2", "TELEPORT_PROJECTILE_SHORT", "TELEPORT_PROJECTILE_SHORT" }, spells_per_cast = 1, spread = -5, speed_multiplier = 1.081, always_cast = { } },
  { name = "wand:3-44", deck = { "PENTAGRAM_SHAPE", "CIRCLE_SHAPE", "ORBIT_LASERS", "FIREBOMB", "FIREBOMB", "FIREBOMB" }, spells_per_cast = 1, spread = -3, speed_multiplier = 1.186, always_cast = { } },
  { name = "wand:4-45", deck = { "LIFETIME_DOWN", "BULLET_TIMER", "BULLET_TIMER" }, spells_per_cast = 1, spread = 6, speed_multiplier = 0.808, always_cast = { } },
  { name = "wand:5-46", deck = { "TENTACLE_PORTAL", "PIPE_BOMB_DEATH_TRIGGER", "FLAMETHROWER", "CRITICAL_HIT" }, spells_per_cast = 2, spread = -3, speed_multiplier = 1.041, always_cast = { } },
  { name = "wand:6-47", deck = { "TELEPORT_PROJECTILE_STATIC", "ROCKET_TIER_2", "ROCKET_TIER_3", "MEGALASER", "EXPANDING_ORB", "GRENADE_TIER_3" }, spells_per_cast = 1, spread = 3, speed_multiplier = 1.025, always_cast = { } },
  { name = "wand:1-48", deck = { "BURST_2", "LIGHT", "RUBBER_BALL", "RUBBER_BALL" }, spells_per_cast = 1, spread = -2, speed_multiplier = 0.958, always_cast = { } },
  { name = "wand:2-49", deck = { "BURST_2", "BURST_2", "BOMB" }, spells_per_cast = 1, spread = -2, speed_multiplier = 0.843, always_cast = { } },
}
