"""Generate C# from the design sheets: one class per sheet, one initializer per row.

  python tools/gen_cs.py --gate 1a     # build: runs preflight for stage 1a first, refuses if not clean
  python tools/gen_cs.py --draft       # generate anyway (marked DRAFT) so code can compile before the
                                       # game-side cells are filled; never ship a draft

Output:
  src/Terranoita.Core/Generated/<Sheet>.g.cs   data tables (no game dependency)
  src/Terranoita/Generated/ZoneChecks.g.cs     terraria_zones.terraria_check compiled as lambdas
"""
import argparse
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import preflight  # noqa: E402

CORE_OUT = os.path.join(ROOT, "src", "Terranoita.Core", "Generated")
GAME_OUT = os.path.join(ROOT, "src", "Terranoita", "Generated")

NAMES = {
    "enemies": ("EnemyDef", "Enemies"),
    "attacks": ("AttackDef", "Attacks"),
    "projectiles": ("ProjectileDef", "Projectiles"),
    "ai_archetypes": ("AiArchetypeDef", "AiArchetypes"),
    "biome_map": ("BiomeMapDef", "BiomeMap"),
    "terraria_zones": ("TerrariaZoneDef", "TerrariaZones"),
    "balance": ("BalanceDef", "Balance"),
    "drops": ("DropDef", "Drops"),
    "systems": ("SystemDef", "Systems"),
    "hooks": ("HookDef", "Hooks"),
    "materials": ("MaterialDef", "Materials"),
}

# object columns: C# type and how each value is written
OBJECT_COLUMNS = {
    ("enemies", "dmg_mult"): "Dictionary<string, float>",
    ("attacks", "damage"): "Dictionary<string, float[]>",
}


def pascal(s):
    return "".join(p[:1].upper() + p[1:] for p in s.replace(".", "_").split("_") if p)


def cs_type(sheet, col, spec):
    t = spec["type"]
    if (sheet, col) in OBJECT_COLUMNS:
        return OBJECT_COLUMNS[(sheet, col)]
    return {"string": "string", "enum": "string", "ref": "string", "number": "float", "int": "int",
            "bool": "bool", "ref[]": "string[]", "string[]": "string[]", "int[]": "int[]",
            "number[]": "float[]"}[t]


def lit_str(v):
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def lit_float(v):
    r = repr(float(v))
    return r + "f"


def literal(sheet, col, spec, v):
    t = cs_type(sheet, col, spec)
    if v is None or v == "":
        return None
    if t == "string":
        return lit_str(v)
    if t == "float":
        return lit_float(v)
    if t == "int":
        return str(int(v))
    if t == "bool":
        return "true" if v else "false"
    if t == "string[]":
        return "new[] { " + ", ".join(lit_str(x) for x in v) + " }" if v else "new string[0]"
    if t == "int[]":
        return "new[] { " + ", ".join(str(int(x)) for x in v) + " }" if v else "new int[0]"
    if t == "float[]":
        return "new[] { " + ", ".join(lit_float(x) for x in v) + " }" if v else "new float[0]"
    if t == "Dictionary<string, float>":
        if any(x is None for x in v.values()):
            return None
        return "new Dictionary<string, float> { " + ", ".join(
            "{ %s, %s }" % (lit_str(k), lit_float(x)) for k, x in v.items()) + " }"
    if t == "Dictionary<string, float[]>":
        items = []
        for k, x in v.items():
            pair = x if isinstance(x, list) else [x, x]
            items.append("{ %s, new[] { %s, %s } }" % (lit_str(k), lit_float(pair[0]), lit_float(pair[1])))
        return "new Dictionary<string, float[]> { " + ", ".join(items) + " }"
    raise ValueError(t)


def gen_sheet(sheet, s, draft):
    cls, table = NAMES[sheet]
    lines = ["// <auto-generated>",
             "// From design/sheets/%s.json by tools/gen_cs.py. Do not edit: change the sheet and regenerate." % sheet]
    if draft:
        lines.append("// DRAFT: generated while preflight is not clean. Unfilled cells are left at their defaults.")
    lines += ["// </auto-generated>", "using System.Collections.Generic;", "",
              "namespace Terranoita.Generated", "{",
              "    /// <summary>%s</summary>" % s["description"],
              "    public sealed partial class %s" % cls, "    {"]
    for col, spec in s["columns"].items():
        lines.append("        /// <summary>%s</summary>" % spec.get("desc", "").replace("&", "&amp;").replace("<", "&lt;"))
        lines.append("        public %s %s;" % (cs_type(sheet, col, spec), pascal(col)))
    lines += ["    }", "", "    public static partial class %s" % table, "    {",
              "        public static readonly %s[] All =" % cls, "        {"]
    for r in s["rows"]:
        parts, missing = [], []
        for col, spec in s["columns"].items():
            lit = literal(sheet, col, spec, r.get(col))
            if lit is None:
                missing.append(col)
            else:
                parts.append("%s = %s" % (pascal(col), lit))
        note = ("  // UNFILLED: " + ", ".join(missing)) if missing else ""
        lines.append("            new %s { %s },%s" % (cls, ", ".join(parts), note))
    lines += ["        };", "    }", "}", ""]
    return "\n".join(lines)


def gen_zone_checks(s, draft):
    lines = ["// <auto-generated>",
             "// From design/sheets/terraria_zones.json (terraria_check) by tools/gen_cs.py. Do not edit."]
    if draft:
        lines.append("// DRAFT: zones without a verified check are null and never spawn.")
    lines += ["// </auto-generated>", "using System;", "using System.Collections.Generic;", "using Terraria;", "using Terraria.ID;", "",
              "namespace Terranoita.Generated", "{", "    public static class ZoneChecks", "    {",
              "        /// <summary>zone id -> check(player, spawn tile x, spawn tile y)</summary>",
              "        public static readonly Dictionary<string, Func<Player, int, int, bool>> All =",
              "            new Dictionary<string, Func<Player, int, int, bool>>", "        {"]
    for r in s["rows"]:
        expr = r.get("terraria_check")
        if expr:
            lines.append("            { %s, (p, x, y) => %s }," % (lit_str(r["id"]), expr))
        else:
            lines.append("            { %s, null },  // UNFILLED: %s" % (lit_str(r["id"]), r["condition"]))
    lines += ["        };", "    }", "}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--gate", choices=preflight.STAGE_ORDER)
    g.add_argument("--draft", action="store_true")
    args = ap.parse_args()

    if args.gate:
        rc = subprocess.call([sys.executable, "-I", os.path.join(ROOT, "tools", "preflight.py"), "--gate", args.gate, "-q"])
        if rc != 0:
            sys.exit("preflight is not clean for stage %s; not generating (use --draft only for compile checks)" % args.gate)

    sheets = preflight.load_sheets()
    os.makedirs(CORE_OUT, exist_ok=True)
    os.makedirs(GAME_OUT, exist_ok=True)
    for name, s in sheets.items():
        if name not in NAMES:
            sys.exit("no C# name for sheet %r; add it to NAMES" % name)
        path = os.path.join(CORE_OUT, NAMES[name][1] + ".g.cs")
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(gen_sheet(name, s, args.draft))
    with open(os.path.join(GAME_OUT, "ZoneChecks.g.cs"), "w", encoding="utf-8", newline="\n") as f:
        f.write(gen_zone_checks(sheets["terraria_zones"], args.draft))
    print("generated %d sheet tables%s" % (len(sheets), " (DRAFT)" if args.draft else ""))


if __name__ == "__main__":
    main()
